from _dsl import *
# 01 · Der Feed gibt dir keine zweite Chance · Flaggschiff · 90 s
def build():
    beats=[
        B("Dein Video hat eins Komma sieben Sekunden.",
          T(P('dein Video hat'), line(N('1,7',**{'from':0.0,'to':1.7,'dec':1,'dur':.5}), A('Sekunden')), size='l'),
          obj={'type':'phone','screen':{'kind':'feed','speed':2.2,'cards':12},'scale':.62,'shift':[0,120],'mode':'depth'},
          layout='textTop', hud={'tcbar':{'start':.2,'dur':1.7}}, sfx=SFX(('hit',0),('rattle',.1))),
        B("Dann ist es weg.",
          T(A('Weggewischt', cls='red'), size='xl'), punch=True, flash=True,
          obj={'type':'phone','screen':{'kind':'feed','speed':6,'cards':6},'scale':.62,'shift':[0,120],'mode':'depth'},
          layout='textTop', hud={'tcbar':{'start':0,'dur':.01}}, sfx=SFX(('swipe',0),('stopp',.15))),
        B("So lange schaut ein Mensch im mobilen Feed im Schnitt auf einen Beitrag.",
          T(P('im mobilen Feed'), line(K('Ein'),A('Beitrag')), D('Ø 1,7 s','cap'), L('Quelle: Facebook IQ, 2016')),
          cursors=[{'name':'CD','path':[[1.6,760,1180],[2.3,640,1010]],'clicks':[2.4]}],
          sfx=SFX(('hit',0),('click',2.4))),
        B("Nicht, weil die Leute ungeduldig sind.",
          T(P('nicht weil'), K('ungeduldig', strike=True, strikeAt=1.3)),
          cursors=[{'name':'Editor','path':[[.8,200,980],[1.3,300,930],[1.9,820,930]],'clicks':[1.3]}],
          sfx=SFX(('hit',0),('strike',1.3))),
        B("Sondern weil der Feed nie leer wird.",
          T(K('Der Feed'), A('wird nie leer')),
          obj={'type':'phone','screen':{'kind':'feed','speed':2.6,'cards':14,'labels':False},'scale':.6,'shift':[0,100],'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0),('whoosh',.3))),
        B("Und die Plattformen schauen genau hin, wer bleibt.",
          T(P('die Plattformen'), line(K('schauen'),A('genau hin')), F('wer bleibt')),
          obj={'type':'curves','series':[{'c':'#3CC9B4','k':'hold','label':'Watch-Time'}],'at':.5,'dur':1.6,'h':480,'mark3':False,'schem':False},
          abs=[{'type':'panel','kind':'graph','x':700,'y':330,'w':320,'at':.9}],
          cursors=[{'name':'QC','path':[[1.0,900,1500],[1.8,780,1380]],'clicks':[1.9]}],
          layout='textTop', sfx=SFX(('hit',0),('click',1.9))),
        B("Wer stehen bleibt, bekommt Reichweite. Wer weggewischt wird, bekommt nichts.",
          T(line(K('Bleibt'),A('oder weg?')), size='m'),
          obj={'type':'split','items':[{'k':'bleibt','v':'Reichweite','cls':'t','bar':.92},{'k':'weggewischt','v':'0','cls':'r','bar':.04}],'at':.4,'step':1.2},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.6),('stopp',1.8))),
        B("Follower spielen dafür eine kleinere Rolle, als die meisten denken.",
          T(K('Follower'), P('kleinere Rolle als gedacht')),
          obj=[{'type':'counter','from':12400,'to':12400,'sm':True,'at':0,'dur':.1,'outAt':1.1,'outDur':.7},
               {'type':'bars','items':[{'k':'','v':78,'c':'t','label':'Watch-Time','at':1.3,'dur':1.0}],'at':1.3}],
          layout='textTop', sfx=SFX(('hit',0),('pitchdown',1.1),('rattle',1.4))),
        B("Das heißt: Jedes Video, das nach einer Sekunde stirbt, hat trotzdem gekostet.",
          T(P('jedes Video'), A('hat trotzdem gekostet'), size='m'),
          obj={'type':'receipt','title':'PRODUKTION · AUSZUG','lines':[{'k':'DREHZEIT','v':'2 h'},{'k':'SCHNITT','v':'3 h'},{'k':'ABSTIMMUNG','v':'1 h'},{'k':'ERGEBNIS','v':'0','tot':True,'red':True}],'at':.3,'printDur':2.8},
          layout='textTop', sfx=SFX(('hit',0),('printer',.3),('printer',1.6))),
        B("Drehzeit. Schnitt. Abstimmung. Nur ohne Ergebnis.",
          T(P('Drehzeit · Schnitt · Abstimmung'), A('ohne Ergebnis'), size='m'),
          obj={'type':'receipt','title':'PRODUKTION · AUSZUG','lines':[{'k':'DREHZEIT','v':'2 h','at':0,'hiAt':.2},{'k':'SCHNITT','v':'3 h','at':0,'hiAt':.7},{'k':'ABSTIMMUNG','v':'1 h','at':0,'hiAt':1.2},{'k':'ERGEBNIS','v':'0','tot':True,'red':True,'at':0}],'at':-3,'printDur':.1,'tearAt':2.4},
          layout='textTop', sfx=SFX(('tick',.2),('tick',.7),('tick',1.2),('tear',2.4))),
        B("Mittelmaß kostet doppelt.",
          T(K('Mittelmaß'), A('kostet doppelt'), size='xl'), bg='cap', punch=True, exit='fade',
          sfx=SFX(('drop',0))),
        B("Was dagegen hilft, ist kein besserer Content-Plan.",
          T(P('was hilft'), K('kein Content-Plan', strike=True, strikeAt=1.4)),
          obj={'type':'calendar','rows':2,'at':.2,'fills':[{'i':0,'c':'grey','at':.3},{'i':3,'c':'grey','at':.45},{'i':8,'c':'grey','at':.6},{'i':11,'c':'grey','at':.75},{'i':0,'c':'grey','at':1.6,'outAt':1.6},{'i':3,'c':'grey','at':1.6,'outAt':1.7},{'i':8,'c':'grey','at':1.6,'outAt':1.8},{'i':11,'c':'grey','at':1.6,'outAt':1.9}]},
          layout='textTop', sfx=SFX(('hit',0),('strike',1.4),('whoosh',1.6))),
        B("Sondern die erste halbe Sekunde.",
          T(K('Die erste'), A('halbe Sekunde'), D('00:00:00:12','cap')), cam='push',
          hud={'tcbar':{'start':.2,'dur':1.7,'stopAt':.294}},
          sfx=SFX(('hit',0),('tick',.3),('stopp',.7))),
        B("Ein Hook aus Bild, Text und Ton, die gleichzeitig zünden.",
          T(line(K('Bild · Text · Ton'),), A('= Hook'), size='m'),
          obj={'type':'cards','items':[{'icon':'eye','label':'Bild'},{'icon':'type','label':'Text'},{'icon':'sound','label':'Ton'}],'at':.3,'step':.18,'mode':'pop'},
          abs=[{'type':'panel','kind':'stagger','x':720,'y':1500,'w':300,'at':1.2}],
          cursors=[{'name':'CD','path':[[.9,900,1700],[1.5,820,1560]],'clicks':[1.6]}],
          layout='textTop', sfx=SFX(('hit',0),('click',.5),('click',.68),('click',.86),('hit',1.2))),
        B("Dann ein Schnitt, der alle zwei bis vier Sekunden etwas Neues zeigt.",
          T(P('alle'), A('2–4 Sekunden'), F('etwas Neues')),
          obj={'type':'timeline','total':12,'marks':[2.5,5,8,10.5],'clips':6,'at':.2,'dur':3.0,'punchOnMark':True},
          layout='textTop', sfx=SFX(('hit',0),('click',1.2),('click',1.85),('click',2.6),('click',3.2))),
        B("Und ein Look, der zeigt, wie gut ihr wirklich seid.",
          T(K('Ein Look'), P('wie gut ihr wirklich seid')),
          obj={'type':'slider','w':760,'h':820,'keys':[[0,.08],[2.6,.92]],'caption':'So stoppst du den *Scroll.'},
          layout='textTop', sfx=SFX(('hit',0),('whoosh',.6),('whoosh',1.6))),
        B("Genau das bauen wir. Für jedes Video. Nach einem System.",
          T(P('genau das'), line(K('bauen wir'),A('nach System')), size='m'),
          obj={'type':'letters','chars':'STOPP','small':True,'at':.5,'step':.14},
          layout='textTop', sfx=SFX(('hit',0),('hit',.5),('hit',.64),('hit',.78),('hit',.92),('hit',1.06))),
        B("Damit Menschen bei eurer Marke stehen bleiben. Und bis zum Ende schauen.",
          T(A('Stehen bleiben'), F('bis zum Ende')),
          obj={'type':'curves','series':[{'c':'#3CC9B4','k':'hold','label':'Mit STOPP'}],'at':.3,'dur':1.8,'h':460,'schem':False,'mark3':False},
          layout='textTop', sfx=SFX(('hit',0),('riser',.3))),
        B("Wenn du wissen willst, wie dein letztes Video in den ersten eins Komma sieben Sekunden abschneidet,",
          T(P('dein letztes Video'), A('1,7 Sekunden'), size='m'),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@deine_marke','caption':'Dein *Hook hier','capSmall':True},'scale':.58,'shift':[0,60],'mode':'rise'},
          layout='textTop', hud={'tcbar':{'start':.4,'dur':1.7}}, sfx=SFX(('hit',0),('tick',.5),('tick',.9),('tick',1.3))),
        B("schreib STOPP in die Kommentare. Wir schauen drauf.",
          T(A('STOPP', size='xl'), P('in die Kommentare')),
          obj={'type':'comments','items':[{'name':'du','text':'STOPP','typing':True,'typeDur':.6,'at':.3,'time':'jetzt','likes':'','replyAt':1.6,'reply':'Antworten ↵'}],'at':.3},
          cursors=[{'name':'Editor','path':[[1.1,900,1500],[1.6,760,1330]],'clicks':[1.65]}],
          layout='textTop', sfx=SFX(('hit',0),('type',.4),('type',.52),('type',.64),('type',.76),('type',.88),('click',1.65))),
    ]
    return {'slug':'der-feed-gibt-dir-keine-zweite-chance','fps':25,'beats':beats,'ident':{'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}}
