from _dsl import *
# 02 · Die STOPP-Methode · Flaggschiff
def build():
    beats=[
        B("Gute Schnitte gibt es viele.",
          T(P('gute Schnitte'), K('gibt es viele')),
          obj={'type':'phone','screen':{'kind':'profile','handle':'irgendeine_marke','sub':'Videos · Reels · Shorts','covers':['Neu','Team','Sale','Tipp','Event','Q&A','Behind','Launch','Promo']},'scale':.6,'shift':[0,80],'mode':'depth'},
          layout='textTop', sfx=SFX(('hit',0),('whoosh',.3))),
        B("Ein System hat fast keiner.",
          T(line(K('Ein'),A('System')), P('hat fast keiner')), punch=True,
          sfx=SFX(('hit',0),('whoosh',.2))),
        B("Deshalb bauen wir jedes Video nach fünf Hebeln.",
          T(P('deshalb'), A('Fünf Hebel'), F('ein System')),
          obj={'type':'letters','chars':'STOPP','small':True,'at':.4,'step':.14},
          abs=[{'type':'panel','kind':'stagger','x':720,'y':1540,'w':300,'at':1.3}],
          cursors=[{'name':'CD','path':[[1.0,880,1750],[1.6,760,1600]],'clicks':[1.7]}],
          layout='textTop', sfx=SFX(('hit',0),('hit',.4),('hit',.54),('hit',.68),('hit',.82),('hit',.96),('click',1.7))),
        B("S wie Scroll-Stopper.",
          T(line(A('S'),K('wie Scroll-Stopper')), size='m'),
          obj={'type':'letters','chars':'STOPP','small':True,'at':0,'step':.04,'hi':0},
          layout='textTop', sfx=SFX(('hit',0))),
        B("Die ersten null Komma fünf Sekunden werden gebaut, nicht nur geschnitten.",
          T(P('die ersten'), A('0,5 Sekunden'), P('gebaut, nicht geschnitten')),
          obj={'type':'cards','items':[{'icon':'eye','label':'Bild'},{'icon':'type','label':'Text'},{'icon':'sound','label':'Ton'}],'at':.9,'step':.16,'mode':'pop'},
          hud={'tcbar':{'start':.1,'dur':1.7,'stopAt':.294}},
          layout='textTop', sfx=SFX(('hit',0),('stopp',.6),('click',.9),('click',1.06),('click',1.22))),
        B("Pro Video drei Hook-Varianten. Frage, Behauptung, Visual.",
          T(D('A · B · C','cap'), K('Frage · Behauptung · Visual'), size='s'),
          obj={'type':'pills','items':[{'s':'A · Frage','cls':'red'},{'s':'B · Behauptung','cls':'teal'},{'s':'C · Visual','cls':''}],'at':.5,'step':.25},
          layout='textTop', sfx=SFX(('hit',0),('click',.5),('click',.75),('click',1.0))),
        B("T wie Taktung.",
          T(line(A('T'),K('wie Taktung')), size='m'),
          obj={'type':'letters','chars':'STOPP','small':True,'at':0,'step':.04,'hi':1},
          layout='textTop', sfx=SFX(('hit',0))),
        B("Kein toter Frame. Pattern-Interrupt alle zwei bis vier Sekunden.",
          T(A('Kein toter Frame'), D('2–4 s','cap')),
          obj={'type':'timeline','total':12,'marks':[2.5,5,8,10.5],'clips':6,'at':.2,'dur':2.8,'punchOnMark':True},
          layout='textTop', sfx=SFX(('hit',0),('click',1.1),('click',1.7),('click',2.4),('click',3.0))),
        B("Wer bleibt, schaut bis zum Ende.",
          T(P('wer bleibt'), A('bis zum Ende')),
          obj={'type':'curves','at':.3,'step':.4,'dur':1.6,'h':520,'axis':['0 s','Ende']},
          layout='textTop', sfx=SFX(('hit',0),('riser',.3))),
        B("O wie Optik.",
          T(line(A('O'),K('wie Optik')), size='m'),
          obj={'type':'letters','chars':'STOPP','small':True,'at':0,'step':.04,'hi':2},
          layout='textTop', sfx=SFX(('hit',0))),
        B("Kino-Look im Hochformat. Color Grading, Motion Graphics, Captions in eurer Schrift, Sound Design.",
          T(A('Kino-Look'), P('Grading · Motion · Captions · Sound'), size='m'),
          obj={'type':'slider','w':720,'h':760,'keys':[[0,.1],[2.4,.9]],'caption':'Kino-Look im *Hochformat'},
          abs=[{'type':'panel','kind':'values','rows':[['Lift R','−.02'],['Gamma R','+.04'],['Gain B','−.02']],'x':720,'y':1560,'w':300,'at':1.0}],
          layout='textTop', sfx=SFX(('hit',0),('rattle',.8),('rattle',1.6))),
        B("Alles aus einer Hand, alles aufeinander abgestimmt.",
          T(P('aus einer Hand'), F('abgestimmt')),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@eure_marke','caption':'Alles *abgestimmt','capSmall':True},'scale':.56,'shift':[0,40],'mode':'pop'},
          layout='textTop', sfx=SFX(('hit',0),('click',.4),('click',.6),('click',.8),('click',1.0))),
        B("P wie Performance.",
          T(line(A('P'),K('wie Performance')), size='m'),
          obj={'type':'letters','chars':'STOPP','small':True,'at':0,'step':.04,'hi':3},
          layout='textTop', sfx=SFX(('hit',0))),
        B("Wir schneiden nach Zahlen.",
          T(A('Nach Zahlen')),
          obj={'type':'table','cols':['KPI','Monat 1','Monat 2'],'rows':[['Hook-Rate','31 %',{'s':'48 %','cls':'teal'}],['Hold-Rate','44 %',{'s':'57 %','cls':'teal'}],['Watch-Time','38 %',{'s':'52 %','cls':'teal'}],['Shares','12',{'s':'41','cls':'teal'}]],'at':.2,'step':.2,'width':900},
          abs=[{'type':'pin','x':700,'y':1620,'text':'Beispielwerte','at':1.2,'tc':''}],
          layout='textTop', sfx=SFX(('hit',0),('rattle',.4))),
        B("Hook A: einunddreißig Prozent. Hook B: achtundvierzig. Hook C: zweiundzwanzig.",
          T(P('Hook-Rate'), L('Beispielwerte'), size='m'),
          obj={'type':'bars','items':[{'k':'A','v':31,'c':'r','at':.3},{'k':'B','v':48,'c':'t','at':1.6,'hiAt':2.4},{'k':'C','v':22,'c':'v','at':2.9}],'label':'Beispielwerte · Hook-Rate = Anteil, der länger als 3 s bleibt'},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.3),('rattle',1.6),('hit',2.4),('rattle',2.9))),
        B("B wird zur Vorlage für den nächsten Monat. Was nicht funktioniert, fliegt raus.",
          T(P('B wird'), A('die Vorlage')),
          obj={'type':'bars','items':[{'k':'A','v':31,'c':'r','at':0,'dur':.1,'dimAt':1.8},{'k':'B','v':48,'c':'t','at':0,'dur':.1,'hiAt':.5},{'k':'C','v':22,'c':'v','at':0,'dur':.1,'dimAt':1.4}]},
          cursors=[{'name':'Editor','path':[[.6,900,1100],[1.0,620,1010],[1.5,620,1010],[2.0,900,1300]],'clicks':[1.0,2.0]}],
          layout='textTop', sfx=SFX(('hit',0),('click',1.0),('whoosh',1.4),('click',2.0))),
        B("Und P wie Pipeline.",
          T(line(A('P'),K('wie Pipeline')), size='m'),
          obj={'type':'letters','chars':'STOPP','small':True,'at':0,'step':.04,'hi':4},
          layout='textTop', sfx=SFX(('hit',0))),
        B("Ein fester Editor, der eure Marke kennt. Lieferung in achtundvierzig bis zweiundsiebzig Stunden.",
          T(P('fester Editor'), A('48–72 h')),
          obj={'type':'pipeline','at':.4,'dur':2.6},
          layout='textTop', sfx=SFX(('hit',0),('tick',.6),('tick',1.3),('tick',2.0),('tick',2.7))),
        B("Feedback per Klick direkt im Video. Ein Kalender, der nie leer läuft.",
          T(P('Feedback per Klick'), A('nie leer')),
          obj=[{'type':'phone','screen':{'kind':'clip','handle':'@eure_marke','pin':{'x':60,'y':560,'tc':'00:00:04:17','text':'Logo 10 % größer','at':.8}},'scale':.5,'shift':[-200,0],'mode':'rise'},
               {'type':'calendar','at':1.6,'fills':[{'i':0,'c':'cap','at':1.9},{'i':2,'c':'cap','at':2.1},{'i':4,'c':'cap','at':2.3}],'height':90}],
          objDir='column', objGap=20, layout='textTop', sfx=SFX(('hit',0),('pling',.8),('tick',1.9),('tick',2.1),('tick',2.3))),
        B("Fünf Hebel. Ein System. Jedes Video.",
          T(line(K('Fünf Hebel.'),A('Ein System.')), size='m'),
          obj={'type':'letters','chars':'STOPP','at':.2,'step':.1,'gatherAt':1.2},
          layout='textTop', cam='push', sfx=SFX(('hit',0),('drop',.9))),
        B("Willst du sehen, wie dein letztes Video nach STOPP geschnitten aussähe?",
          T(P('dein letztes Video'), line(K('nach'),A('STOPP')), size='m'),
          obj={'type':'slider','w':640,'h':700,'keys':[[0,.5],[2.5,.5]],'caption':'Dein *Video','left':'HEUTE','right':'NACH STOPP'},
          layout='textTop', sfx=SFX(('hit',0))),
        B("Schick uns den Link per DM. Wir zeigen es dir.",
          T(A('Per DM'), P('Link schicken, wir zeigen es dir')),
          obj={'type':'phone','screen':{'kind':'dm','title':'Daumenstopp','items':[{'name':'du','text':'Hier ist mein letztes Reel: …'},{'name':'Daumenstopp','text':'Danke! Drei Dinge würden wir ändern …'}],'at':.4},'scale':.56,'shift':[0,40],'mode':'rise'},
          cursors=[{'name':'Editor','path':[[1.2,800,1500],[1.7,700,1360]],'clicks':[1.75]}],
          layout='textTop', sfx=SFX(('hit',0),('pling',1.75))),
    ]
    return {'slug':'die-stopp-methode','fps':25,'beats':beats,'ident':{'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}}
