from _dsl import *
# 03 · Was High-End konkret heißt · Flaggschiff (8 Entscheidungen)
def card(n,icon,label): return {'n':n,'icon':icon,'label':label}
def build():
    beats=[
        B("Premium ist kein Gefühl.",
          T(K('Premium'), P('ist kein Gefühl')),
          obj={'type':'slider','w':760,'h':820,'keys':[[0,.5],[.4,.5],[1.2,.56],[2.0,.46]],'caption':'Premium ist kein *Gefühl'},
          layout='textTop', sfx=SFX(('hit',0))),
        B("Es ist eine Reihe von Entscheidungen, die man sieht und hört.",
          T(A('Entscheidungen'), F('sieht und hört')),
          obj={'type':'cards','items':[{'n':1,'icon':'film','label':'4K'},{'n':2,'icon':'palette','label':'Grading'},{'n':3,'icon':'sound','label':'Sound'},{'n':4,'icon':'text','label':'Captions'},{'n':5,'icon':'layers','label':'Formate'},{'n':6,'icon':'motion','label':'Motion'},{'n':7,'icon':'eye','label':'QC 2×'},{'n':8,'icon':'doc','label':'Rechte'}],'at':.4,'step':.1,'mode':'pop','width':960,'small':True},
          layout='textTop', sfx=SFX(('hit',0))+[{'name':'tick','at':.4+i*.1} for i in range(8)]),
        B("Acht davon trifft jedes unserer Videos.",
          T(line(N('8',**{'from':0,'to':8,'dur':.6}),A('/ 8')), P('jedes Video')),
          cursors=[{'name':'CD','path':[[.8,860,1300],[1.3,700,1150]],'clicks':[1.35]}],
          sfx=SFX(('hit',0),('rattle',.1),('click',1.35))),
        B("Eins. Schnitt in bis zu vier K. Export in tausendachtzig mal neunzehnhundertzwanzig mit hoher Bitrate.",
          T(line(D('01','cap'),A('4K')), D('2160p → 1080 × 1920')),
          obj={'type':'split','items':[{'k':'Daumenstopp','v':'scharf','cls':'t','bar':.98},{'k':'Standard-Export','v':'matschig','cls':'r','bar':.35}],'at':.6,'step':.5},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.6))),
        B("Damit nichts matschig komprimiert wird.",
          T(P('nichts matschig'), A('komprimiert'), size='m'), punch=True,
          sfx=SFX(('hit',0),('whoosh',.3))),
        B("Zwei. Color Grading für jeden Clip. Belichtung, Weißabgleich, Hauttöne.",
          T(line(D('02','cap'),A('Color Grading')), P('Belichtung · Weißabgleich · Hauttöne'), size='m'),
          obj={'type':'slider','w':720,'h':700,'keys':[[0,.1],[2.6,.9]],'caption':'Jeder *Clip'},
          abs=[{'type':'panel','kind':'values','rows':[['Lift R','−.02 · B +.03'],['Gamma R','+.04 · G +.01'],['Gain R','+.06 · B −.02']],'x':700,'y':1580,'w':320,'at':1.0}],
          layout='textTop', sfx=SFX(('hit',0),('rattle',.9),('rattle',1.8))),
        B("Dazu ein eigener Look für eure Marke.",
          T(F('euer Look', extra=0), size='m'),
          obj={'type':'cards','items':[{'icon':'palette','label':'LUT · [[Marke]]','hi':True}],'at':.3,'mode':'pop','wide':True},
          layout='textTop', sfx=SFX(('hit',0),('click',.5))),
        B("Drei. Sound Design und Mastering. Dialog gesäubert, Musik gesetzt, minus vierzehn LUFS.",
          T(line(D('03','cap'),A('−14 LUFS')), P('Dialog · Musik · Effekte'), size='m'),
          obj={'type':'wave','dirty':True,'cleanAt':1.2,'bars':56,'h':240},
          layout='textTop', sfx=SFX(('hit',0),('buzz',.4),('pling',1.4))),
        B("Vier. Animierte Captions, Wort für Wort, in eurer Schrift. Korrekturgelesen.",
          T(line(D('04','cap'),A('Captions')), P('Wort für Wort · korrekturgelesen'), size='m'),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@eure_marke','caption':'Wort für *Wort in eurer Schrift','capStep':.22},'scale':.56,'shift':[0,30],'mode':'rise'},
          cursors=[{'name':'QC','path':[[1.9,880,1500],[2.4,700,1380]],'clicks':[2.45]}],
          layout='textTop', sfx=SFX(('hit',0),('type',.3),('type',.52),('type',.74),('type',.96),('type',1.18),('haken',2.45))),
        B("Weil viele ohne Ton schauen.",
          T(P('viele schauen ohne Ton'), size='m'),
          obj={'type':'icobox','icon':'mute','color':'var(--rec)','size':300,'pulse':True},
          layout='textTop', sfx=SFX(('hit',0),('pitchdown',.2))),
        B("Fünf. Jedes Format. Neun zu sechzehn, vier zu fünf, eins zu eins, sechzehn zu neun.",
          T(line(D('05','cap'),A('Jedes Format')), size='m'),
          obj={'type':'pills','items':[{'s':'9:16','cls':'on'},{'s':'4:5'},{'s':'1:1'},{'s':'16:9'}],'at':.6,'step':.3},
          layout='textTop', sfx=SFX(('hit',0),('click',.6),('click',.9),('click',1.2),('click',1.5))),
        B("Texte bleiben in den Safe Zones. Nie unter Buttons.",
          T(A('Safe Zones'), P('nie unter Buttons'), size='m'),
          obj={'type':'uiov','at':.2,'zoneAt':{'bottom':.9,'right':1.1},'safeAt':1.8,'abs':True,'x':0,'y':0,'enter':False},
          layout='textTop', sfx=SFX(('hit',0),('buzz',.9),('haken',1.8))),
        B("Sechs. Custom Motion Graphics. Gebaut, nicht aus dem Template-Regal.",
          T(line(D('06','cap'),A('Custom Motion')), P('kein Template-Regal'), size='m'),
          obj={'type':'cards','items':[{'icon':'motion','label':'Logo-Animation'},{'icon':'layers','label':'Lower Third'},{'icon':'bolt','label':'Übergänge'}],'at':.4,'step':.2,'mode':'pop'},
          abs=[{'type':'panel','kind':'graph','x':700,'y':1560,'w':320,'at':1.2}],
          layout='textTop', sfx=SFX(('hit',0),('click',.4),('click',.6),('click',.8))),
        B("Sieben. Vier-Augen-Prinzip. Ein zweiter Editor prüft vor jeder Lieferung.",
          T(line(D('07','cap'),A('QC 2×')), P('zweiter Editor vor jeder Lieferung'), size='m'),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@eure_marke','caption':'Qualiät','capAnim':False,'capCls':'plain'},'scale':.56,'shift':[0,30],'mode':'rise'},
          cursors=[{'name':'Editor','path':[[.3,220,1200],[.3,220,1200]]},{'name':'QC','path':[[1.2,900,1600],[1.9,560,1270]],'clicks':[1.95]}],
          layout='textTop', sfx=SFX(('hit',0),('click',1.95),('haken',2.2))),
        B("Tippfehler und Patzer erreichen euch nicht.",
          T(P('Tippfehler und Patzer'), A('erreichen euch nicht'), size='m'),
          obj={'type':'checklist','items':[{'s':'Rechtschreibung','at':.3},{'s':'Safe Zones','at':.6},{'s':'Lautheit −14 LUFS','at':.9},{'s':'Export 1080 × 1920','at':1.2}],'width':820},
          layout='textTop', sfx=SFX(('hit',0),('haken',.65),('haken',.95),('haken',1.25),('haken',1.55))),
        B("Acht. Volle Nutzungsrechte. Organisch und bezahlt. Musik lizenziert.",
          T(line(D('08','cap'),A('Nutzungsrechte')), D('© inkl.','cap'), size='m'),
          obj={'type':'cards','items':[{'icon':'doc','label':'Organisch'},{'icon':'euro','label':'Bezahlt'},{'icon':'sound','label':'Musik lizenziert'}],'at':.4,'step':.2,'mode':'pop'},
          layout='textTop', sfx=SFX(('hit',0),('haken',.5),('haken',.7),('haken',.9))),
        B("Acht Entscheidungen. Jedes Video. Das ist High-End bei uns.",
          T(line(K('Acht Entscheidungen.'),), A('High-End'), size='m'), cam='push',
          obj={'type':'phone','screen':{'kind':'clip','handle':'@eure_marke','caption':'*High-End'},'scale':.56,'shift':[0,30],'mode':'depth','glow':True},
          layout='textTop', sfx=SFX(('hit',0),('drop',.4))),
        B("Zieh den Regler selbst. Den Vorher-Nachher-Vergleich findest du im Profil.",
          T(P('zieh selbst'), A('Vorher / Nachher'), P('Link im Profil'), size='m'),
          obj={'type':'slider','w':720,'h':700,'keys':[[0,.5],[.6,.5],[1.2,.62],[1.8,.4],[2.4,.5]],'caption':'Zieh *selbst'},
          layout='textTop', sfx=SFX(('hit',0),('whoosh',1.2),('whoosh',1.8))),
    ]
    return {'slug':'was-high-end-konkret-heisst','fps':25,'beats':beats,'ident':{'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}}
