from _dsl import *
# 04 · Die ehrliche Rechnung · Flaggschiff (Vergleichstabelle)
COLS=['Kriterium','Daumenstopp','Inhouse','Freelancer','Selbst']
def build():
    beats=[
        B("Ein Inhouse-Editor kostet rund viertausendfünfhundert Euro im Monat.",
          T(P('ein Inhouse-Editor'), A('4.500 €'), L('pro Monat · ²')),
          obj={'type':'receipt','title':'INHOUSE-EDITOR · PRO MONAT','lines':[{'k':'GEHALT BRUTTO','v':'3.600 €'},{'k':'AG-ANTEILE ca. 21 %','v':'756 €'},{'k':'HARDWARE','v':'anteilig'},{'k':'SOFTWARE','v':'anteilig'},{'k':'SUMME','v':'≈ 4.500 €','tot':True}],'at':.3,'printDur':3.0},
          layout='textTop', sfx=SFX(('hit',0),('printer',.3),('printer',1.7))),
        B("Und das ist nicht das Problem.",
          T(K('nicht'), A('das Problem'), size='xl'), punch=True,
          sfx=SFX(('hit',0),('tear',.1))),
        B("Video-Content kannst du auf vier Arten lösen.",
          T(P('vier Arten'), size='m'),
          obj={'type':'table','cols':COLS,'rows':[],'at':.3},
          cursors=[{'name':'CD','path':[[.6,300,1000],[1.0,480,980],[1.4,660,980],[1.8,840,980]],'clicks':[.6,1.0,1.4,1.8]}],
          layout='textTop', sfx=SFX(('hit',0),('click',.6),('click',1.0),('click',1.4),('click',1.8))),
        B("Selbst machen. Kostet nichts. Außer acht bis zwölf Stunden deiner Woche.",
          T(P('selbst machen'), line(D('0 €'),A('8–12 h / Woche')), size='m'),
          obj=[{'type':'clock','keys':[[.4,0],[2.2,720]],'fmt':'h','sm':True},
               {'type':'calendar','at':.6,'fills':[{'i':0,'c':'red','at':.8},{'i':1,'c':'red','at':1.0},{'i':2,'c':'red','at':1.2},{'i':3,'c':'red','at':1.4},{'i':4,'c':'red','at':1.6}],'height':90}],
          layout='textTop', sfx=SFX(('hit',0),('rattle',.5),('rattle',1.2))),
        B("Jede Woche. Statt Vertrieb, Produkt, Team.",
          T(P('jede Woche'), K('statt'), size='m'),
          obj={'type':'pills','items':[{'s':'Vertrieb','outAt':1.0},{'s':'Produkt','outAt':1.2},{'s':'Team','outAt':1.4}],'at':.2,'step':.15},
          layout='textTop', sfx=SFX(('hit',0),('whoosh',1.0),('whoosh',1.2),('whoosh',1.4))),
        B("Freelancer. Schwankend im Preis, startklar in ein bis drei Wochen.",
          T(P('Freelancer'), line(D('schwankend'),A('1–3 Wochen')), size='m'),
          obj={'type':'counter','from':900,'to':2400,'sm':True,'suffix':' €','at':.3,'dur':1.6,'ease':'lin'},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.3),('rattle',1.0))),
        B("Gut, solange die Person Zeit hat. Urlaub, Krankheit, anderer Kunde: Pause.",
          T(P('solange die Person Zeit hat'), A('Pause', cls='red'), size='m'),
          obj={'type':'calendar','rows':2,'at':.3,'fills':[{'i':0,'c':'teal','at':.5},{'i':1,'c':'teal','at':.6},{'i':2,'c':'red','at':1.2},{'i':3,'c':'red','at':1.3},{'i':4,'c':'red','at':1.4},{'i':7,'c':'teal','at':1.6},{'i':9,'c':'red','at':2.0},{'i':10,'c':'red','at':2.1}],'height':100},
          layout='textTop', sfx=SFX(('hit',0),('buzz',1.2),('buzz',2.0))),
        B("Inhouse. Viertausendfünfhundert im Monat, startklar in sechs bis zwölf Wochen.",
          T(P('Inhouse'), line(A('4.500 €'),D('6–12 Wochen')), size='m'),
          obj={'type':'calendar','days':['W1','W2','W3','W4','W5','W6','W7','W8','W9','W10','W11','W12'],'strip':True,'at':.3,'fills':[{'i':i,'c':'grey','at':.5+i*.14} for i in range(12)],'height':90},
          layout='textTop', sfx=SFX(('hit',0))+[{'name':'tick','at':.5+i*.14} for i in range(12)]),
        B("Hook-Strategie, Motion, Sound Design: je nach Person.",
          T(P('Hook-Strategie · Motion · Sound'), K('je nach Person'), size='m'),
          obj={'type':'cards','items':[{'icon':'q','label':'Hook-Strategie'},{'icon':'q','label':'Motion'},{'icon':'q','label':'Sound Design'}],'at':.3,'step':.2,'mode':'pop'},
          layout='textTop', sfx=SFX(('hit',0),('click',.3),('click',.5),('click',.7))),
        B("Skalieren von acht auf zwanzig Videos heißt: Neueinstellung.",
          T(line(D('8 → 20'),), A('Neueinstellung'), size='m'),
          obj={'type':'receipt','title':'ZWEITER EDITOR','lines':[{'k':'GEHALT BRUTTO','v':'3.600 €'},{'k':'AG-ANTEILE','v':'756 €'},{'k':'SUMME','v':'≈ 4.500 €','tot':True}],'at':.4,'printDur':2.2},
          layout='textTop', sfx=SFX(('hit',0),('printer',.4))),
        B("Daumenstopp.",
          T(A('Daumenstopp', size='xl')), punch=True, flash=True,
          sfx=SFX(('hit',0))),
        B("Startklar in sieben Tagen. Fester Editor. Zweiter Blick vor jeder Lieferung.",
          T(A('7 Tage'), P('fester Editor · QC 2×'), size='m'),
          obj={'type':'checklist','items':[{'s':'Startklar in 7 Tagen','at':.3},{'s':'Fester Editor','at':.7},{'s':'Zweiter Blick vor Lieferung','at':1.1}],'width':860},
          cursors=[{'name':'QC','path':[[1.0,900,1500],[1.5,300,1330]],'clicks':[1.55]}],
          layout='textTop', sfx=SFX(('hit',0),('haken',.65),('haken',1.05),('haken',1.45))),
        B("Hook-Strategie und Auswertung inklusive. Motion und Sound aus einer Hand.",
          T(P('inklusive'), size='m'),
          obj={'type':'checklist','items':[{'s':'Hook-Strategie','at':.2},{'s':'Auswertung','at':.5},{'s':'Motion Graphics','at':.8},{'s':'Sound Design','at':1.1}],'width':860},
          layout='textTop', sfx=SFX(('hit',0),('haken',.55),('haken',.85),('haken',1.15),('haken',1.45))),
        B("Vertretung bei Urlaub und Krankheit. Immer.",
          T(P('Vertretung'), F('immer', extra=.1), size='m'),
          obj={'type':'calendar','rows':2,'at':.2,'fills':[{'i':i,'c':'teal','at':.4+i*.08} for i in range(14)],'height':100},
          layout='textTop', sfx=SFX(('hit',0),('riser',.3))),
        B("Von acht auf zwanzig Videos skalierbar. Sofort. Ohne Neueinstellung.",
          T(line(D('8 → 20'),), A('Sofort'), size='m'),
          obj={'type':'counter','from':8,'to':20,'at':.4,'dur':1.0,'stopPop':True},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.4),('hit',1.4))),
        B("Ab [[Preis]] Euro im Monat.",
          T(line(K('ab'),A('[[Preis]] €')), L('netto · pro Monat · Platzhalter'), size='m'),
          sfx=SFX(('hit',0),('rattle',.2))),
        B("Rechne es selbst. Deine Zeit, dein Gehalt, deine Ausfälle.",
          T(A('Rechne selbst'), P('Zeit · Gehalt · Ausfälle'), size='m'),
          obj={'type':'table','cols':COLS,'rows':[['Kosten / Monat',{'s':'ab [[Preis]]','cls':'cap'},'≈ 4.500 €','schwankend','8–12 h'],['Startklar',{'s':'7 Tage','cls':'cap'},'6–12 Wo.','1–3 Wo.','sofort'],['Hook-Strategie',{'t':'chk'},'selten','selten',{'t':'x'}],['Motion & Sound',{'t':'chk'},'je nach Person','je nach Person',{'t':'x'}],['Vertretung',{'t':'chk'},{'t':'x'},{'t':'x'},{'t':'x'}],['QC vor Lieferung',{'t':'chk'},{'t':'x'},{'t':'x'},{'t':'x'}],['8 → 20 skalierbar',{'s':'sofort','cls':'cap'},'Neueinstellung','begrenzt',{'t':'x'}]],'at':.2,'step':.18,'hiCol':1,'width':960},
          cursors=[{'name':'CD','path':[[1.8,460,900],[2.6,460,1500]],'clicks':[]}],
          layout='textTop', sfx=SFX(('hit',0))+[{'name':'tick','at':.4+i*.18} for i in range(7)]),
        B("Die ganze Tabelle mit allen Zahlen schicken wir dir. Kommentier RECHNUNG.",
          T(A('RECHNUNG', size='xl'), P('in die Kommentare'), size='m'),
          obj={'type':'comments','items':[{'name':'du','text':'RECHNUNG','typing':True,'typeDur':.7,'at':.3,'time':'jetzt'}],'at':.3},
          layout='textTop', sfx=SFX(('hit',0))+[{'name':'type','at':.4+i*.09} for i in range(8)]),
        B("Die Annahme hinter den viertausendfünfhundert steht unten in der Caption.",
          T(L('² Annahme: 3.600 € brutto + ca. 21 % AG-Anteile + Hardware/Software'), L('ohne Recruiting, Einarbeitung, Ausfallzeiten'), size='s'),
          sfx=SFX(('tick',0))),
    ]
    return {'slug':'die-ehrliche-rechnung','fps':25,'beats':beats,'ident':{'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}}
