from _dsl import *
# 05 · In 7 Tagen live · Flaggschiff (72 Minuten)
IDENT={'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}
DAYS=['T0','T1','T2','T3','T4','T5','T6','T7']
def build():
    beats=[
        B("Vom Ja bis zum ersten fertigen Video: sieben Tage.",
          T(P('vom Ja bis zum Video'), A('7 Tage')),
          obj={'type':'calendar','days':DAYS,'strip':True,'at':.3,'fills':[{'i':0,'c':'cap','at':.6}],'height':100},
          layout='textTop', sfx=SFX(('hit',0),('tick',.6))),
        B("Dein Aufwand in dieser Woche: zweiundsiebzig Minuten. Ich rechne vor.",
          T(A('72 min'), F('ich rechne vor')),
          obj={'type':'clock','keys':[[0,0],[.1,0]],'fmt':'min'},
          cursors=[{'name':'Editor','path':[[1.2,760,1300],[1.7,560,1200]],'clicks':[1.75]}],
          layout='textTop', sfx=SFX(('hit',0),('click',1.75))),
        B("Tag null. Du nimmst das Angebot an. Zwei Minuten.",
          T(line(D('Tag 0','cap'),K('Annahme')), D('+ 2 min'), size='m'),
          obj=[{'type':'clock','keys':[[.9,0],[1.5,2]],'fmt':'min','sm':True},
               {'type':'cards','items':[{'icon':'doc','label':'Angebot annehmen →','hiAt':1.0}],'at':.3,'mode':'pop','wide':True}],
          cursors=[{'name':'Du','path':[[.5,900,1500],[1.0,560,1390]],'clicks':[1.0]}],
          layout='textTop', sfx=SFX(('hit',0),('click',1.0),('rattle',1.0))),
        B("Innerhalb von vierundzwanzig Stunden: Auftragsbestätigung, Vertrag, Rechnung. Ohne Papierkram bei dir.",
          T(P('innerhalb von 24 h'), P('ohne Papierkram bei dir'), size='m'),
          obj={'type':'cards','items':[{'icon':'doc','label':'Bestätigung'},{'icon':'doc','label':'Vertrag'},{'icon':'doc','label':'Rechnung'}],'at':.5,'step':.25,'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0),('whoosh',.5),('whoosh',.75),('whoosh',1.0))),
        B("Tag eins bis zwei. Kickoff-Call. Fünfundvierzig Minuten.",
          T(line(D('Tag 1–2','cap'),A('Kickoff')), D('+ 45 min'), size='m'),
          obj=[{'type':'clock','keys':[[.8,2],[1.8,47]],'fmt':'min','sm':True},
               {'type':'cards','items':[{'icon':'people','label':'Call · 45 min','hi':True}],'at':.3,'mode':'pop','wide':True}],
          layout='textTop', sfx=SFX(('hit',0),('rattle',.8))),
        B("Wir lernen eure Marke, eure Zielgruppe und eure Ziele kennen. Und legen die Content-Säulen fest.",
          T(P('Marke · Zielgruppe · Ziele'), A('Content-Säulen'), size='m'),
          obj={'type':'cards','items':[{'icon':'target','label':'Säule 1'},{'icon':'target','label':'Säule 2'},{'icon':'target','label':'Säule 3'}],'at':1.0,'step':.2,'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0),('click',1.0),('click',1.2),('click',1.4))),
        B("Tag zwei bis vier. Strategie, Hook-Bank, Style-Frame. Zehn Minuten.",
          T(line(D('Tag 2–4','cap'),A('Style-Frame')), D('+ 10 min'), size='m'),
          obj=[{'type':'clock','keys':[[.8,47],[1.5,57]],'fmt':'min','sm':True},
               {'type':'cards','items':[{'icon':'type','label':'Schrift'},{'icon':'palette','label':'Farben'},{'icon':'text','label':'Captions'},{'icon':'motion','label':'Motion'}],'at':.4,'step':.14,'mode':'pop','width':940}],
          layout='textTop', sfx=SFX(('hit',0),('click',.4),('click',.54),('click',.68),('click',.82),('rattle',.8))),
        B("Du siehst vorab, wie euer Look aussehen wird. Erst nach deinem Okay schneiden wir.",
          T(P('erst nach deinem Okay'), size='m'),
          obj={'type':'checklist','items':[{'s':'Style-Frame freigegeben','at':.4,'checkDelay':1.1}],'width':860},
          cursors=[{'name':'Du','path':[[.6,900,1400],[1.4,170,1130]],'clicks':[1.5]}],
          layout='textTop', sfx=SFX(('hit',0),('click',1.5),('haken',1.55))),
        B("Tag fünf bis sieben. Erste Lieferung. Fünfzehn Minuten.",
          T(line(D('Tag 5–7','cap'),A('Erste Lieferung')), D('+ 15 min'), size='m'),
          obj=[{'type':'clock','keys':[[.8,57],[1.6,72]],'fmt':'min','sm':True},
               {'type':'cards','items':[{'icon':'play','label':'Video 1'},{'icon':'play','label':'Video 2'},{'icon':'play','label':'Video 3'}],'at':.3,'step':.15,'mode':'pop'}],
          layout='textTop', sfx=SFX(('hit',0),('pling',.3),('rattle',.8))),
        B("Feedback gibst du per Klick direkt an der Stelle im Video.",
          T(P('Feedback per Klick'), size='m'),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@eure_marke','pin':{'x':70,'y':520,'tc':'00:00:04:17','text':'Logo 10 % größer','at':.9}},'scale':.58,'shift':[0,30],'mode':'rise'},
          cursors=[{'name':'Du','path':[[.3,900,1500],[.85,420,1180]],'clicks':[.9]}],
          layout='textTop', sfx=SFX(('hit',0),('click',.9),('pling',1.0))),
        B("Zweiundsiebzig Minuten. Erste Videos live.",
          T(line(A('72 min'),K('→'),A('live', cls='teal')), size='l'), punch=True,
          obj={'type':'clock','keys':[[0,72],[.1,72]],'fmt':'min'},
          layout='textTop', sfx=SFX(('stopp',0),('pling',.4))),
        B("Ab Woche zwei: feste Lieferzyklen, monatlicher Report, Strategie-Call.",
          T(P('Lieferzyklen · Report · Call'), A('ab Woche 2'), size='m'),
          obj={'type':'calendar','rows':2,'at':.3,'fills':[{'i':0,'c':'cap','at':.6},{'i':2,'c':'cap','at':.8},{'i':4,'c':'cap','at':1.0},{'i':7,'c':'cap','at':1.3},{'i':9,'c':'cap','at':1.5},{'i':11,'c':'cap','at':1.7}],'height':100},
          layout='textTop', sfx=SFX(('hit',0),('tick',.6),('tick',.8),('tick',1.0),('tick',1.3),('tick',1.5),('tick',1.7))),
        B("Dein Aufwand danach: rund eine Stunde im Monat.",
          T(A('1 h / Monat'), P('dein Aufwand danach')),
          obj={'type':'clock','keys':[[.3,0],[1.4,60]],'fmt':'min'},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.3))),
        B("Du filmst oder lieferst Material. Alles andere übernehmen wir.",
          T(P('du filmst'), A('alles andere wir'), size='m'),
          obj={'type':'pipeline','at':.4,'dur':2.4},
          layout='textTop', sfx=SFX(('hit',0),('tick',.6),('tick',1.2),('tick',1.8),('tick',2.4))),
        B("Wann willst du starten? Schreib den Monat in die Kommentare.",
          T(A('Wann?'), P('schreib den Monat in die Kommentare'), size='l'),
          obj={'type':'comments','items':[{'name':'du','text':'[[Monat]]','typing':True,'typeDur':.6,'at':.4,'time':'jetzt'}],'at':.4},
          layout='textTop', sfx=SFX(('hit',0),('type',.5),('type',.6),('type',.7),('type',.8))),
        B("Im [[November]] haben wir Platz für [[zwei]] neue Marken.",
          T(P('im [[November]]'), A('[[zwei]] Plätze'), size='m'),
          obj={'type':'slots','n':2,'labels':['Marke','Marke'],'onAt':[.8,None],'at':.3},
          layout='textTop', sfx=SFX(('hit',0),('click',.3),('click',.42),('hit',.8))),
    ]
    return {'slug':'in-7-tagen-live','fps':25,'beats':beats,'ident':IDENT}
