from _dsl import *
# 06 · Testen statt raten · Flaggschiff (A/B/C Quiz)
IDENT={'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}
def phones(mode='rise',hi=None):
    items=[]
    for i,(h,cap) in enumerate([('A','Warum sieht das *keiner?'),('B','Hör auf, *so zu posten.'),('C','Wir haben es *getestet.')]):
        items.append({'type':'phone','screen':{'kind':'clip','seed':i,'handle':'@test','tc':False,'ui':False,'caption':cap,'capSmall':True,'capAt':.2,'capStep':.1},'w':300,'mode':mode,'at':.2+i*.12})
    return items
def build():
    beats=[
        B("Dasselbe Video. Drei Anfänge.",
          T(P('dasselbe Video'), A('Drei Anfänge')),
          obj=phones(), objDir='row', objGap=24,
          layout='textTop', sfx=SFX(('hit',0),('hit',.2),('hit',.32),('hit',.44))),
        B("Einer bringt mehr als doppelt so viel wie der schwächste.",
          T(A('Mehr als doppelt'), P('so viel wie der schwächste'), size='m'),
          obj={'type':'bars','items':[{'k':'?','v':40,'c':'grey','suffix':'','at':.3},{'k':'?','v':70,'c':'grey','suffix':'','at':.5},{'k':'?','v':30,'c':'grey','suffix':'','at':.7}]},
          layout='textTop', sfx=SFX(('hit',0),('riser',.3))),
        B("Welcher? Rate mal. Ich löse gleich auf.",
          T(K('Welcher?'), F('rate mal', extra=.1), size='l'),
          obj={'type':'cards','items':[{'big':'A','label':'Frage'},{'big':'B','label':'Behauptung'},{'big':'C','label':'Visual'}],'at':.3,'step':.15,'mode':'pop'},
          layout='textTop', sfx=SFX(('hit',0),('click',.3),('click',.45),('click',.6))),
        B("Variante A. Eine Frage: Warum sieht das keiner?",
          T(line(D('A','red'),P('Frage')), line(K('Warum sieht das'),A('keiner?')), size='m'),
          obj={'type':'phone','screen':{'kind':'clip','seed':0,'handle':'@test','caption':'Warum sieht das *keiner?','capAt':.4},'scale':.58,'shift':[0,20],'mode':'rise'},
          cursors=[{'name':'Editor','path':[[.6,900,1500],[1.1,700,1360]],'clicks':[1.15]}],
          layout='textTop', sfx=SFX(('hit',0),('click',1.15))),
        B("Variante B. Eine Behauptung: Hör auf, so zu posten.",
          T(line(D('B','teal'),P('Behauptung')), line(K('Hör auf,'),A('so'),K('zu posten.')), size='m'),
          obj={'type':'phone','screen':{'kind':'clip','seed':1,'handle':'@test','caption':'Hör auf, *so zu posten.','capAt':.4},'scale':.58,'shift':[0,20],'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0),('click',.5))),
        B("Variante C. Ein Bild: Wir haben es getestet.",
          T(line(D('C','cap'),P('Visual')), line(K('Wir haben es'),A('getestet.')), size='m'),
          obj={'type':'slider','w':640,'h':640,'keys':[[0,.1],[1.8,.9]],'caption':'Wir haben es *getestet','tc':False},
          layout='textTop', sfx=SFX(('hit',0),('whoosh',.4))),
        B("Alle drei laufen eine Woche. Gleiche Zielgruppe, gleiche Zeit, gleiches Budget.",
          T(P('Zielgruppe · Zeit · Budget'), A('gleich'), size='m'),
          obj={'type':'calendar','rows':3,'at':.3,'fills':[{'i':i,'c':['red','teal','cap'][i//7],'at':.5+(i%7)*.12} for i in range(21)],'height':70},
          layout='textTop', sfx=SFX(('hit',0))+[{'name':'tick','at':.5+i*.12} for i in range(7)]),
        B("Wir messen eine Zahl: die Hook-Rate.",
          T(A('Hook-Rate'), L('Anteil, der länger als 3 Sekunden bleibt')),
          hud={'tcbar':{'start':.2,'dur':3.0,'stopAt':1.0,'tealLabel':'3 s · bleibt'}},
          sfx=SFX(('hit',0),('tick',.5),('tick',1.0),('tick',1.5),('stopp',3.2))),
        B("A: einunddreißig Prozent.",
          T(line(D('A','red'),K('Hook-Rate')), L('Beispielwerte'), size='m'),
          obj={'type':'bars','items':[{'k':'A','v':31,'c':'r','at':.2}]},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.2))),
        B("C: zweiundzwanzig Prozent.",
          T(line(D('C','cap'),K('Hook-Rate')), L('Beispielwerte'), size='m'),
          obj={'type':'bars','items':[{'k':'A','v':31,'c':'r','at':0,'dur':.05},{'k':'C','v':22,'c':'v','at':.2}]},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.2))),
        B("B: achtundvierzig Prozent.",
          T(line(D('B','teal'),K('Hook-Rate')), L('Beispielwerte'), size='m'), punch=True,
          obj={'type':'bars','items':[{'k':'A','v':31,'c':'r','at':0,'dur':.05,'dimAt':1.2},{'k':'B','v':48,'c':'t','at':.2,'hiAt':1.0},{'k':'C','v':22,'c':'v','at':0,'dur':.05,'dimAt':1.2}]},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.2),('drop',.6))),
        B("Mehr als doppelt so viele Menschen bleiben stehen. Beim selben Video.",
          T(A('2,2×'), P('beim selben Video'), size='xl'),
          obj={'type':'split','items':[{'k':'C','v':'22 %','cls':'r','bar':.22},{'k':'B','v':'48 %','cls':'t','bar':.48}],'at':.3,'step':.3},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.5))),
        B("Hätten wir geraten, hätten wir vielleicht A genommen. Klingt ja gut.",
          T(P('hätten wir geraten'), K('Variante A', strike=True, strikeAt=1.6), size='m'),
          obj={'type':'cards','items':[{'big':'A','label':'Frage','dimAt':1.6},{'big':'B','label':'Behauptung','hiAt':1.9},{'big':'C','label':'Visual'}],'at':.2,'step':.1,'mode':'pop'},
          cursors=[{'name':'CD','path':[[.8,900,1500],[1.5,260,1180]],'clicks':[1.6]}],
          layout='textTop', sfx=SFX(('hit',0),('strike',1.6),('click',1.9))),
        B("Deshalb bekommt jedes Video ab dem Paket Momentum drei Hook-Varianten.",
          T(P('deshalb'), A('3 Hooks'), P('ab Paket Momentum'), size='m'),
          obj={'type':'cards','items':[{'icon':'bolt','label':'Momentum · 12 Videos · 3 Hooks','hi':True}],'at':.5,'mode':'pop','wide':True},
          layout='textTop', sfx=SFX(('hit',0),('click',.5))),
        B("Und B wird zur Vorlage für die nächsten Videos. Was funktioniert, bauen wir aus.",
          T(line(D('B','teal'),K('= Vorlage')), F('bauen wir aus'), size='m'),
          obj={'type':'cards','items':[{'icon':'book','label':'Hook-Bank','hiAt':1.2}],'at':.3,'mode':'pop','wide':True},
          cursors=[{'name':'Editor','path':[[.5,200,1100],[1.2,540,1180]],'clicks':[1.25]}],
          layout='textTop', sfx=SFX(('hit',0),('click',1.25))),
        B("Testen statt raten. Jeden Monat.",
          T(A('Testen'), K('statt raten', strike=True, strikeAt=.6), size='xl'), bg='cap', punch=True, exit='fade',
          sfx=SFX(('drop',0),('strike',.6))),
        B("Welchen Hook hättest du genommen? Kommentier A, B oder C.",
          T(A('A, B oder C?'), P('kommentier deine Wahl'), size='l'),
          obj={'type':'comments','items':[{'name':'lisa.m','text':'B! Klar.','at':.3,'likes':'12'},{'name':'tom_k','text':'A, oder?','at':.7,'likes':'3'},{'name':'du','text':'…','typing':True,'typeDur':.2,'at':1.1,'time':'jetzt'}],'at':.3},
          layout='textTop', sfx=SFX(('hit',0),('whoosh',.3),('whoosh',.7),('type',1.2))),
        B("Die Zahlen hier sind Beispielwerte aus unserem Testaufbau. Eure messen wir live.",
          T(L('Beispielwerte · Testaufbau', 'cap'), P('eure messen wir live'), size='m'),
          sfx=SFX(('tick',0))),
    ]
    return {'slug':'testen-statt-raten','fps':25,'beats':beats,'ident':IDENT}
