from _dsl import *
# 07 · Case: [[Kunde]] in 90 Tagen · Flaggschiff-Template (Platzhalter!)
IDENT={'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}
def build():
    beats=[
        B("[[Kunde]] hat Content nebenbei gemacht.",
          T(P('[[Kunde]]'), K('nebenbei')),
          obj={'type':'phone','screen':{'kind':'clip','flat':True,'handle':'@[[handle]]','ui':False,'tc':False},'scale':.58,'shift':[0,40],'mode':'depth'},
          layout='textTop', sfx=SFX(('hit',0))),
        B("Neunzig Tage später: [[Ergebnis in einer Zahl]].",
          T(A('[[Zahl]]', size='xl'), L('nach 90 Tagen · Platzhalter')),
          obj={'type':'counter','from':0,'to':90,'suffix':' Tage','sm':True,'at':.3,'dur':1.0},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.3))),
        B("So sah es vorher aus.",
          T(K('Vorher'), size='l'),
          obj={'type':'pills','items':[{'s':'[[Content entsteht nebenbei.]]','at':.4},{'s':'[[Nach 1–2 Sekunden weggewischt.]]','at':.7},{'s':'[[Kein System hinter Hooks.]]','at':1.0}],'width':940},
          layout='textTop', sfx=SFX(('hit',0),('whoosh',.4),('whoosh',.7),('whoosh',1.0))),
        B("Videos wurden nach ein, zwei Sekunden weggewischt.",
          T(A('Weggewischt', cls='red'), size='xl'),
          obj={'type':'phone','screen':{'kind':'feed','speed':4,'cards':8,'labels':True},'scale':.56,'shift':[0,40],'mode':'rise'},
          hud={'tcbar':{'start':.1,'dur':1.7}},
          layout='textTop', sfx=SFX(('swipe',0),('tick',.5),('tick',1.0),('tick',1.5),('stopp',1.8))),
        B("Das Ziel: drei Videos pro Woche, fest im Kalender. Hooks, die stoppen. Ein Look, den man erkennt.",
          T(A('Das Ziel'), P('3 / Woche · Hooks · Look'), size='m'),
          obj={'type':'calendar','rows':2,'at':.3,'fills':[{'i':0,'c':'cap','at':.8},{'i':2,'c':'cap','at':1.0},{'i':4,'c':'cap','at':1.2},{'i':7,'c':'cap','at':1.5},{'i':9,'c':'cap','at':1.7},{'i':11,'c':'cap','at':1.9}],'height':100},
          layout='textTop', sfx=SFX(('hit',0),('tick',.8),('tick',1.0),('tick',1.2),('tick',1.5),('tick',1.7),('tick',1.9))),
        B("Was wir gemacht haben.",
          T(K('Was wir'), A('gemacht haben'), size='l'),
          obj={'type':'letters','chars':'STOPP','small':True,'at':.3,'step':.12},
          layout='textTop', sfx=SFX(('hit',0),('hit',.3),('hit',.42),('hit',.54),('hit',.66),('hit',.78))),
        B("Drei Hook-Varianten pro Video. Getestet, nicht geraten.",
          T(D('A · B · C','cap'), A('Getestet'), size='m'),
          obj={'type':'bars','items':[{'k':'A','v':31,'c':'r','at':.3},{'k':'B','v':48,'c':'t','at':.6},{'k':'C','v':22,'c':'v','at':.9}],'label':'Beispielwerte'},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.3),('rattle',.6),('rattle',.9))),
        B("Pattern-Interrupt alle zwei bis vier Sekunden.",
          T(A('2–4 s'), P('Pattern-Interrupt'), size='l'),
          obj={'type':'timeline','total':12,'marks':[2.5,5,8,10.5],'clips':6,'at':.2,'dur':2.6,'punchOnMark':True},
          layout='textTop', sfx=SFX(('hit',0),('click',1.0),('click',1.6),('click',2.2),('click',2.8))),
        B("Grading, Captions in der Markenschrift, Sound Design.",
          T(P('Grading · Captions · Sound'), size='m'),
          obj={'type':'slider','w':720,'h':760,'keys':[[0,.1],[2.4,.9]],'caption':'[[Kunde]] in der *Markenschrift'},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.8),('pling',1.6))),
        B("Und jeden Monat: Zahlen lesen, Hooks nachschärfen.",
          T(A('Nach Zahlen'), P('jeden Monat'), size='m'),
          obj={'type':'table','cols':['KPI','Monat 1','Monat 3'],'rows':[['Hook-Rate','[[xx]] %',{'s':'[[yy]] %','cls':'teal'}],['Watch-Time','[[xx]] %',{'s':'[[yy]] %','cls':'teal'}],['[[Kennzahl]]','[[xx]]',{'s':'[[yy]]','cls':'teal'}]],'at':.3,'width':900},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.4))),
        B("Das Ergebnis nach neunzig Tagen.",
          T(P('das Ergebnis nach'), A('90 Tagen'), size='l'), punch=True,
          sfx=SFX(('hit',0),('riser',.2))),
        B("Hook-Rate: von [[xx]] auf [[yy]] Prozent.",
          T(L('Hook-Rate'), line(D('[[xx]] %'),K('→'),A('[[yy]] %')), size='m'),
          obj={'type':'bars','items':[{'k':'vor','v':30,'c':'r','at':.2,'suffix':' %'},{'k':'nach','v':55,'c':'t','at':.8,'hiAt':1.6,'suffix':' %'}],'label':'Platzhalter · echte Werte aus dem Report'},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.2),('rattle',.8),('hit',1.6))),
        B("Watch-Time: von [[xx]] auf [[yy]] Prozent.",
          T(L('Watch-Time'), line(D('[[xx]] %'),K('→'),A('[[yy]] %')), size='m'),
          obj={'type':'bars','items':[{'k':'vor','v':35,'c':'r','at':.2},{'k':'nach','v':58,'c':'t','at':.8,'hiAt':1.6}],'label':'Platzhalter'},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.2),('rattle',.8),('hit',1.6))),
        B("[[Weitere Kennzahl, zum Beispiel Reichweite, Saves, Anfragen]].",
          T(L('[[Kennzahl]]'), A('[[Wert]]', size='xl'), size='m'),
          obj={'type':'counter','from':0,'to':100,'suffix':'','sm':True,'at':.3,'dur':1.2},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.3),('hit',1.5))),
        B("Und es hat Reaktionen gegeben.",
          T(K('Es hat'), F('Reaktionen', extra=.1), size='l'),
          obj={'type':'comments','items':[{'name':'[[user]]','text':'[[Echter Kommentar 1]]','at':.4,'likes':'[[n]]'},{'name':'[[user]]','text':'[[Echter Kommentar 2]]','at':.9,'likes':'[[n]]'}],'at':.4},
          layout='textTop', sfx=SFX(('hit',0),('whoosh',.4),('whoosh',.9))),
        B("[[Zitat des Kunden, zwei Sätze: Ergebnis und Gefühl der Zusammenarbeit.]]",
          T(P('[[Name]] · [[Rolle]], [[Firma]]'), K('„[[Zitat Satz 1.]]“', size='m'), A('„[[Zitat Satz 2.]]“', size='m'), size='s'),
          sfx=SFX(('hit',0))),
        B("Drei Videos pro Woche. Ein Look. Ein System. Seit neunzig Tagen.",
          T(line(D('3 / Woche','cap'),K('· Ein Look ·'),A('Ein System')), size='s'),
          obj={'type':'phone','screen':{'kind':'profile','handle':'[[handle]]','sub':'[[Claim des Kunden]]'},'scale':.58,'shift':[0,30],'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0),('click',.3))),
        B("Willst du wissen, wie das für eure Marke aussähe?",
          T(P('für eure Marke'), A('Wie sähe das aus?'), size='m'),
          obj={'type':'phone','screen':{'kind':'blank'},'scale':.5,'shift':[0,30],'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0))),
        B("Schreib CASE in die Kommentare. Wir zeigen dir weitere Projekte aus eurer Branche.",
          T(A('CASE', size='xl'), P('in die Kommentare'), size='m'),
          obj={'type':'comments','items':[{'name':'du','text':'CASE','typing':True,'typeDur':.5,'at':.3,'time':'jetzt'}],'at':.3},
          layout='textTop', sfx=SFX(('hit',0),('type',.4),('type',.52),('type',.64),('type',.76))),
    ]
    return {'slug':'case-kunde-in-90-tagen','fps':25,'beats':beats,'ident':IDENT}
