from _dsl import *
# 08 · Die Daumenstopp-Garantie · Flaggschiff
IDENT={'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}
def build():
    beats=[
        B("Wenn dich unsere erste Lieferung nicht überzeugt, zahlst du nichts.",
          T(P('erste Lieferung nicht überzeugt?'), A('Zahlst du nichts'), size='l'), bg='cap', punch=True, exit='fade',
          sfx=SFX(('stamp',0),('hit',.1))),
        B("Klingt nach Marketing. Ist aber eine Rechnung.",
          T(P('klingt nach Marketing'), A('Ist eine Rechnung'), size='m'),
          sfx=SFX(('hit',0),('whoosh',.2))),
        B("Bevor wir das erste Video schneiden, stimmen wir mit dir einen Style-Frame ab.",
          T(P('bevor wir schneiden'), A('Style-Frame'), size='m'),
          obj={'type':'cards','items':[{'icon':'type','label':'Schrift'},{'icon':'palette','label':'Farben'},{'icon':'text','label':'Captions'},{'icon':'motion','label':'Motion'}],'at':.4,'step':.14,'mode':'pop','width':940},
          cursors=[{'name':'Du','path':[[1.4,900,1600],[2.0,540,1180]],'clicks':[2.05]}],
          layout='textTop', sfx=SFX(('hit',0),('click',.4),('click',.54),('click',.68),('click',.82),('haken',2.05))),
        B("Schrift, Farben, Captions, Motion. Du siehst den Look, bevor er existiert.",
          T(P('Schrift · Farben · Captions · Motion'), F('bevor er existiert', extra=.1), size='m'),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@eure_marke','caption':'Euer *Look','capStep':.2},'scale':.56,'shift':[0,30],'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0),('tick',.3),('tick',.5),('tick',.7),('tick',.9))),
        B("Deshalb sitzt der Look meistens schon bei der ersten Lieferung.",
          T(P('deshalb'), A('sitzt beim ersten Mal'), size='m'),
          obj={'type':'checklist','items':[{'s':'Erste Lieferung','val':'✓','at':.4}],'width':860},
          layout='textTop', sfx=SFX(('hit',0),('haken',.8))),
        B("Und falls nicht:",
          T(K('Falls'), A('nicht', cls='red'), size='xl'),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@eure_marke','pin':{'x':60,'y':560,'tc':'00:00:06:04','text':'Captions größer, Logo früher','at':.5}},'scale':.56,'shift':[0,30],'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0),('pling',.5))),
        B("Wir überarbeiten, bis es passt. Nicht einmal, nicht zweimal. Bis es passt.",
          T(A('Bis es passt'), D('v1 → v2 → v3','cap'), size='m'),
          obj={'type':'pills','items':[{'s':'v1','at':.3},{'s':'v2','at':1.0},{'s':'v3','cls':'cap','at':1.7}],'at':.3},
          layout='textTop', sfx=SFX(('hit',0),('click',.3),('click',1.0),('click',1.7))),
        B("Und wenn dich die Lieferung dann immer noch nicht überzeugt:",
          T(P('und wenn dann immer noch'), A('nicht überzeugt', cls='red'), size='m'), cam='push',
          sfx=SFX(('hit',0),('riser',.4))),
        B("Zahlst du für den ersten Monat nichts.",
          T(A('0,00 €', size='xl'), L('erster Monat')),
          obj={'type':'receipt','title':'DAUMENSTOPP · ERSTER MONAT','lines':[{'k':'8 VIDEOS','v':'geliefert'},{'k':'ÜBERARBEITUNGEN','v':'3'},{'k':'ÜBERZEUGT?','v':'nein','red':True},{'k':'GESAMT','v':'0,00 €','tot':True}],'at':.3,'printDur':2.6},
          layout='textTop', sfx=SFX(('hit',0),('printer',.3),('printer',1.6))),
        B("Kein Kleingedrucktes, das die Garantie wieder einsammelt. Nur zwei Bedingungen.",
          T(P('kein Kleingedrucktes'), A('Nur zwei Bedingungen'), size='m'),
          obj={'type':'slots','n':2,'labels':['Bedingung','Bedingung'],'at':.4,'w':260},
          layout='textTop', sfx=SFX(('hit',0),('click',.4),('click',.52))),
        B("Gilt für den ersten Leistungsmonat.",
          T(line(D('1','cap'),A('Erster Monat')), size='m'),
          obj={'type':'slots','n':2,'labels':['Erster Monat','Bedingung'],'onAt':[.3,None],'at':0,'w':260},
          layout='textTop', sfx=SFX(('hit',0),('haken',.3))),
        B("Und für Neukunden.",
          T(line(D('2','cap'),A('Neukunden')), size='m'),
          obj={'type':'slots','n':2,'labels':['Erster Monat','Neukunden'],'onAt':[0,.3],'at':0,'w':260},
          layout='textTop', sfx=SFX(('hit',0),('haken',.3))),
        B("Warum wir uns das leisten können?",
          T(K('Warum?'), size='xl'),
          cursors=[{'name':'CD','path':[[.4,900,1300],[.9,640,1000]],'clicks':[.95]}],
          sfx=SFX(('hit',0),('click',.95))),
        B("Weil wir nach Zahlen schneiden. Drei Hook-Varianten, Vier-Augen-Prinzip, Style-Frame vorab.",
          T(A('Nach Zahlen'), size='l'),
          obj={'type':'cards','items':[{'icon':'graph','label':'3 Hook-Varianten'},{'icon':'eye','label':'Vier-Augen-Prinzip'},{'icon':'palette','label':'Style-Frame vorab'}],'at':.6,'step':.25,'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0),('click',.6),('click',.85),('click',1.1))),
        B("Wer das macht, liefert selten etwas, das nicht überzeugt.",
          T(P('selten'), F('überzeugt', extra=.1), size='m'),
          obj={'type':'curves','series':[{'c':'#3CC9B4','k':'hold','label':'Überzeugt'}],'at':.3,'dur':1.6,'h':420,'mark3':False,'schem':False},
          layout='textTop', sfx=SFX(('hit',0),('riser',.3))),
        B("Du gehst kein Risiko ein. Wir schon. Und das ist richtig so.",
          T(A('Kein Risiko'), P('für dich · wir schon'), size='l'), bg='cap', punch=True, exit='fade',
          sfx=SFX(('drop',0))),
        B("Fünfzehn Minuten reichen, um zu klären, ob wir zusammenpassen. Link im Profil.",
          T(A('15 min'), P('Link im Profil'), size='l'),
          obj={'type':'calendar','rows':1,'at':.3,'fills':[{'i':2,'c':'cap','at':.8}],'height':110},
          layout='textTop', sfx=SFX(('hit',0),('pling',.8))),
    ]
    return {'slug':'die-daumenstopp-garantie','fps':25,'beats':beats,'ident':IDENT}
