from _dsl import *
# 09 · Drei Gründe, warum dein Video weggewischt wird · Mittel
IDENT={'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}
def build():
    beats=[
        B("Dein Video wird weggewischt. Aus einem von drei Gründen.",
          T(A('Weggewischt', cls='red'), P('aus einem von drei Gründen')),
          obj={'type':'pills','items':[{'s':'1'},{'s':'2'},{'s':'3'}],'at':1.2,'step':.15},
          hud={'tcbar':{'start':.1,'dur':1.7}},
          layout='textTop', sfx=SFX(('swipe',0),('hit',.1),('click',1.2),('click',1.35),('click',1.5))),
        B("Grund eins: Dein Anfang ist ein Anlauf.",
          T(line(D('1','cap'),A('Ein Anlauf')), size='l'),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@marke','caption':'Hallo, ich bin …','capCls':'plain','capSmall':True,'capAt':.5,'capStep':.25,'cover':'LOGO'},'scale':.58,'shift':[0,30],'mode':'rise'},
          hud={'tcbar':{'start':.3,'dur':1.7}},
          layout='textTop', sfx=SFX(('hit',0),('tick',.5),('tick',1.0),('tick',1.5))),
        B("Logo, Begrüßung, Vorstellung. Nach eins Komma sieben Sekunden ist der Mensch weg. Dein Inhalt hat noch nicht angefangen.",
          T(P('Logo · Hallo · Vorstellung'), line(D('1,7 s','red'),A('weg', cls='red')), size='m'),
          obj={'type':'phone','screen':{'kind':'feed','speed':5,'cards':24},'scale':.56,'shift':[0,30],'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0),('swipe',1.2),('stopp',1.4))),
        B("Stattdessen: Der erste Frame ist schon die Aussage. Bild, Text, Ton gleichzeitig.",
          T(P('stattdessen'), A('Der erste Frame'), size='m'),
          obj={'type':'cards','items':[{'icon':'eye','label':'Bild'},{'icon':'type','label':'Text'},{'icon':'sound','label':'Ton'}],'at':1.2,'step':.12,'mode':'pop'},
          hud={'tcbar':{'start':.2,'dur':1.7,'stopAt':.294}},
          layout='textTop', sfx=SFX(('hit',0),('stopp',.7),('click',1.2),('click',1.32),('click',1.44))),
        B("Grund zwei: Nichts passiert.",
          T(line(D('2','cap'),A('Nichts passiert')), size='l'),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@marke','frozen':True,'ui':False},'scale':.58,'shift':[0,30],'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0),('tick',1.0),('tick',2.0))),
        B("Zehn Sekunden dieselbe Einstellung. Das Auge hat nichts Neues, das Hirn schaltet ab.",
          T(P('dieselbe Einstellung'), D('00:00:10:00'), size='m'),
          obj={'type':'curves','series':[{'c':'#FF6B8B','k':'fall','label':'Retention'}],'at':.4,'dur':2.0,'h':460,'axis':['0 s','10 s']},
          layout='textTop', sfx=SFX(('hit',0),('pitchdown',.6))),
        B("Stattdessen: Alle zwei bis vier Sekunden etwas Neues. Zoom, Text, B-Roll, Sound-Akzent.",
          T(P('stattdessen'), A('2–4 Sekunden'), size='m'),
          obj=[{'type':'timeline','total':12,'marks':[2.5,5,8,10.5],'clips':6,'at':.2,'dur':2.6,'punchOnMark':True},
               {'type':'pills','items':['Zoom','Text','B-Roll','Sound'],'at':1.2,'step':.2}],
          layout='textTop', sfx=SFX(('hit',0),('click',1.0),('click',1.6),('click',2.2),('click',2.8))),
        B("Grund drei: Dein Video ist stumm.",
          T(line(D('3','cap'),A('Stumm')), size='l'),
          obj={'type':'icobox','icon':'mute','color':'var(--rec)','size':300,'pulse':True},
          layout='textTop', sfx=SFX(('hit',0),('pitchdown',.3))),
        B("Viele schauen ohne Ton. Wenn dann kein Text da ist, gibt es nichts zu verstehen.",
          T(P('viele schauen ohne Ton'), K('nichts zu verstehen'), size='m'),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@marke','muted':True,'ui':False,'cover':'?'},'scale':.56,'shift':[0,30],'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0,.2,.4))),
        B("Stattdessen: Captions, Wort für Wort, in deiner Schrift, korrekturgelesen.",
          T(P('stattdessen'), A('Captions'), size='l'),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@marke','caption':'Wort für *Wort in deiner Schrift','capStep':.2},'scale':.56,'shift':[0,30],'mode':'rise'},
          cursors=[{'name':'QC','path':[[1.6,900,1500],[2.1,660,1360]],'clicks':[2.15]}],
          layout='textTop', sfx=SFX(('hit',0),('type',.3),('type',.5),('type',.7),('type',.9),('type',1.1),('haken',2.15))),
        B("Welchen der drei machst du gerade? Kommentier eins, zwei oder drei. Keine Scham, wir haben alle drei gemacht.",
          T(A('1, 2 oder 3?'), P('keine Scham, wir hatten alle drei'), size='l'),
          obj={'type':'comments','items':[{'name':'du','text':'2','typing':True,'typeDur':.2,'at':.6,'time':'jetzt'}],'at':.6},
          layout='textTop', sfx=SFX(('hit',0),('tick',.3),('tick',.45),('tick',.6),('type',.8))),
    ]
    return {'slug':'drei-gruende','fps':25,'beats':beats,'ident':IDENT}
