from _dsl import *
# 12 · Alle zwei bis vier Sekunden · Mittel (das Video zählt seine Interrupts)
IDENT={'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}
def cnt(n): return {'type':'pin','x':720,'y':1600,'text':f'Interrupts: {n:02d}','at':0,'noAnim':True}
def build():
    beats=[
        B("Der Hook holt sie. Die Taktung hält sie.",
          T(K('Der Hook holt.'), A('Die Taktung hält.')),
          obj={'type':'curves','at':.4,'step':.5,'dur':1.6,'h':480,'axis':['0 s','Ende']},
          layout='textTop', sfx=SFX(('hit',0),('riser',.4))),
        B("Nach dem Hook hat das Hirn eine Frage: Lohnt es sich zu bleiben?",
          T(P('nach dem Hook'), A('Lohnt es sich?'), size='m'),
          hud={'tcbar':{'start':.1,'dur':1.7,'stopAt':.294}},
          obj={'type':'icobox','icon':'q','size':300,'pulse':True}, layout='textTop',
          sfx=SFX(('hit',0),('stopp',.6))),
        B("Die Antwort fällt alle zwei bis vier Sekunden neu.",
          T(A('Alle 2–4 Sekunden'), P('fällt die Antwort neu'), size='m'),
          obj={'type':'timeline','total':12,'marks':[2.5,5,8,10.5],'clips':6,'at':.2,'dur':2.6,'punchOnMark':True},
          abs=[cnt(3)], layout='textTop', sfx=SFX(('hit',0),('click',1.0),('click',1.6),('click',2.2),('click',2.8))),
        B("Wenn nichts Neues kommt, geht das Hirn. Nicht aus Langeweile. Aus Effizienz.",
          T(P('nicht aus Langeweile'), A('Aus Effizienz'), size='m'),
          obj={'type':'curves','series':[{'c':'#FF6B8B','k':'fall','label':'ohne Interrupts'}],'at':.3,'dur':1.8,'h':440,'mark3':False},
          abs=[cnt(3)], layout='textTop', sfx=SFX(('hit',0),('swipe',1.6))),
        B("Fünf Dinge, die als „neu“ zählen.",
          T(A('Fünf Dinge'), P('die als „neu“ zählen'), size='l'),
          obj={'type':'pills','items':[{'s':'1'},{'s':'2'},{'s':'3'},{'s':'4'},{'s':'5'}],'at':.5,'step':.12},
          abs=[cnt(3)], layout='textTop', sfx=SFX(('hit',0))+[{'name':'tick','at':.5+i*.12} for i in range(5)]),
        B("Eins. Zoom-Punch. Zehn Prozent reichen.",
          T(line(D('1','cap'),A('Zoom')), D('+ 10 %'), size='l'), punch=.1,
          obj={'type':'icobox','icon':'zoom','size':280}, abs=[cnt(4)], layout='textTop', sfx=SFX(('hit',0))),
        B("Zwei. Text. Ein Wort, das die nächste Frage stellt.",
          T(line(D('2','cap'),A('Text')), F('ein Wort', extra=.1), size='l'),
          obj={'type':'icobox','icon':'type','size':280}, abs=[cnt(5)], layout='textTop', sfx=SFX(('hit',0),('hit',.5))),
        B("Drei. B-Roll. Zwei Sekunden anderes Bild, dann zurück.",
          T(line(D('3','cap'),A('B-Roll')), P('zwei Sekunden anderes Bild'), size='l'),
          obj={'type':'phone','screen':{'kind':'clip','seed':2,'handle':'@b-roll','ui':False,'tc':False},'scale':.5,'shift':[0,20],'mode':'pop','outAt':2.2,'outDur':.4},
          abs=[cnt(6)], layout='textTop', sfx=SFX(('hit',0),('whoosh',.2),('whoosh',2.2))),
        B("Vier. Sound-Akzent. Ein Riser, ein Klick, eine Pause.",
          T(line(D('4','cap'),A('Sound')), P('Riser · Klick · Pause'), size='l'),
          obj={'type':'wave','bars':56,'h':220,'spikeAt':.8,'freq':8}, abs=[cnt(7)], layout='textTop',
          sfx=SFX(('hit',0),('riser',.3),('click',1.1),('silence',1.2))),
        B("Fünf. Perspektive. Kamera, Farbe oder Ebene wechseln.",
          T(line(D('5','cap'),A('Perspektive')), P('Kamera · Farbe · Ebene'), size='l'), flash=True, cam='push',
          obj={'type':'icobox','icon':'persp','size':280}, abs=[cnt(8)], layout='textTop', sfx=SFX(('hit',0),('whoosh',.1))),
        B("Dieses Video hat bis hierhin acht davon. Du bist noch da. Das ist der Beweis.",
          T(A('Acht', size='xl'), P('du bist noch da'), F('das ist der Beweis', extra=.1), size='m'),
          obj={'type':'curves','series':[{'c':'#3CC9B4','k':'hold','label':'du'}],'at':.3,'dur':1.6,'h':380,'mark3':False,'schem':False},
          layout='textTop', sfx=SFX(('drop',0))),
        B("Speicher dir die fünf. Dein nächster Schnitt wird länger gesehen.",
          T(A('Speichern'), P('dein nächster Schnitt wird länger gesehen'), size='l'),
          obj={'type':'checklist','items':[{'s':'Zoom-Punch','at':.3},{'s':'Text','at':.5},{'s':'B-Roll','at':.7},{'s':'Sound-Akzent','at':.9},{'s':'Perspektive','at':1.1}],'width':820},
          layout='textTop', sfx=SFX(('hit',0),('haken',.65),('haken',.85),('haken',1.05),('haken',1.25),('haken',1.45),('pling',1.6))),
    ]
    return {'slug':'alle-zwei-bis-vier-sekunden','fps':25,'beats':beats,'ident':IDENT}
