from _dsl import *
# 13 · Ohne Ton · Mittel (startet stumm)
IDENT={'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}
def build():
    beats=[
        B(None, T(K('Du hörst gerade'), A('nichts.')), dur=3.6,
          obj={'type':'phone','screen':{'kind':'clip','handle':'@marke','muted':True,'ui':False,'caption':'Du hörst gerade *nichts.','capAt':.3,'capStep':.3},'scale':.56,'shift':[0,30],'mode':'rise'},
          layout='textTop', sfx=[]),
        B(None, T(P('so schauen viele'), A('dein Video')), dur=3.0,
          obj={'type':'phone','screen':{'kind':'feed','speed':1.2,'cards':8,'labels':False},'scale':.56,'shift':[0,30],'mode':'rise'},
          layout='textTop', sfx=[]),
        B("Jetzt mit Ton. Und du merkst: Der Text hat bis hierhin alles getragen.",
          T(P('jetzt mit Ton'), A('Der Text hat getragen'), size='m'), punch=True,
          obj=[{'type':'icobox','icon':'mute','icon2':'speaker','color':'var(--rec)','color2':'var(--cap)','swapAt':0,'size':240},{'type':'wave','bars':56,'h':200,'freq':7}],
          objGap=30, layout='textTop', sfx=SFX(('drop',0),('pling',.5))),
        B("Captions sind kein Untertitel. Sie sind die Hälfte deines Videos.",
          T(P('kein Untertitel'), A('Die Hälfte'), size='l'),
          obj={'type':'split','items':[{'k':'Bild','v':'50 %','cls':'p','bar':.5},{'k':'Captions','v':'50 %','cls':'c','bar':.5}],'at':.4,'step':.4},
          layout='textTop', sfx=SFX(('hit',0),('click',.4),('click',.8))),
        B("Drei Fehler machen sie wertlos.",
          T(A('Drei Fehler'), size='xl'),
          obj={'type':'pills','items':['1','2','3'],'at':.4,'step':.15}, layout='textTop',
          sfx=SFX(('hit',0),('tick',.4),('tick',.55),('tick',.7))),
        B("Eins. Zu klein. Wenn man sie suchen muss, liest sie keiner.",
          T(line(D('1','cap'),A('Zu klein')), size='l'),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@marke','caption':'wer liest das','capCls':'plain small','capAt':.2,'capStep':.1},'scale':.56,'shift':[0,30],'mode':'rise'},
          cursors=[{'name':'QC','path':[[1.0,900,1500],[1.6,620,1300]],'clicks':[1.65]}],
          layout='textTop', punch=False, sfx=SFX(('hit',0),('click',1.65))),
        B("Zwei. Automatisch und ungelesen. „Daumenstopp“ wird zu „Daumen stopp“, „Reichweite“ zu „Reich weite“.",
          T(line(D('2','cap'),A('Ungelesen')), line(D('Daumen stopp','red'),K('→'),D('Daumenstopp','teal')), size='m'),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@marke','caption':'Daumen stopp Reich weite','capCls':'plain','capAt':.2,'capStep':.15},'scale':.56,'shift':[0,30],'mode':'rise'},
          cursors=[{'name':'QC','path':[[1.4,900,1500],[1.9,560,1330],[2.6,700,1330]],'clicks':[1.95,2.6]}],
          layout='textTop', sfx=SFX(('hit',0),('type',1.95),('type',2.1),('haken',2.6))),
        B("Drei. Unter den Buttons. Rechts Like, Kommentar, Share. Unten die Caption der Plattform. Alles, was darunter liegt, ist weg.",
          T(line(D('3','cap'),A('Unter den Buttons')), size='l'),
          obj={'type':'uiov','at':.3,'zoneAt':{'bottom':1.4,'right':1.8},'safeAt':3.2,'abs':True,'x':0,'y':0,'enter':False},
          layout='textTop', sfx=SFX(('hit',0),('buzz',1.4),('buzz',1.8),('haken',3.2))),
        B("Wort für Wort animiert, in eurer Schrift, korrekturgelesen, in der Safe Zone. So sehen Captions bei uns aus.",
          T(P('Wort für Wort · Markenschrift · korrekturgelesen · Safe Zone'), A('So bei uns'), size='m'),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@eure_marke','caption':'So sehen *Captions bei uns aus','capStep':.18},'scale':.56,'shift':[0,30],'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0))+[{'name':'type','at':.3+i*.18} for i in range(6)]),
        B("Schalt den Ton aus und schau nochmal. Du wirst alles verstehen.",
          T(A('Ton aus, nochmal'), P('du wirst alles verstehen'), size='l'),
          obj={'type':'icobox','icon':'speaker','icon2':'mute','color':'var(--cap)','color2':'var(--rec)','swapAt':1.2,'size':280},
          layout='textTop', sfx=SFX(('hit',0),('pitchdown',1.2))),
    ]
    return {'slug':'ohne-ton','fps':25,'beats':beats,'ident':IDENT,'bedStart':6.6}
