from _dsl import *
# 14 · Mittelmaß kostet doppelt · Mittel (zwei Bons)
IDENT={'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}
def build():
    beats=[
        B("Mittelmaß kostet doppelt.",
          T(K('Mittelmaß'), A('kostet doppelt'), size='xl'), bg='cap', punch=True, exit='fade',
          sfx=SFX(('drop',0))),
        B("Ich zeige dir die Rechnung.",
          T(F('die Rechnung', extra=0), size='l'),
          obj={'type':'receipt','title':'ERSTE RECHNUNG','lines':[],'at':.2,'printDur':.6,'barcode':False},
          layout='textTop', sfx=SFX(('hit',0),('printer',.3))),
        B("Ein Video. Drehzeit [[zwei]] Stunden.",
          T(line(D('DREHZEIT'),A('[[2 h]]')), L('Beispielwerte'), size='m'),
          obj={'type':'receipt','title':'ERSTE RECHNUNG · BEISPIEL','lines':[{'k':'DREHZEIT','v':'[[2 h]]','at':.4}],'at':-1,'printDur':.1},
          layout='textTop', sfx=SFX(('hit',0),('printer',.3,.5))),
        B("Schnitt [[drei]] Stunden.",
          T(line(D('SCHNITT'),A('[[3 h]]')), size='m'),
          obj={'type':'receipt','title':'ERSTE RECHNUNG · BEISPIEL','lines':[{'k':'DREHZEIT','v':'[[2 h]]','at':0},{'k':'SCHNITT','v':'[[3 h]]','at':.3}],'at':-1,'printDur':.1},
          layout='textTop', sfx=SFX(('hit',0),('printer',.2,.5))),
        B("Abstimmung, Korrekturen, Freigabe: [[eine]] Stunde.",
          T(line(D('ABSTIMMUNG'),A('[[1 h]]')), size='m'),
          obj={'type':'receipt','title':'ERSTE RECHNUNG · BEISPIEL','lines':[{'k':'DREHZEIT','v':'[[2 h]]','at':0},{'k':'SCHNITT','v':'[[3 h]]','at':0},{'k':'ABSTIMMUNG','v':'[[1 h]]','at':.3}],'at':-1,'printDur':.1},
          layout='textTop', sfx=SFX(('hit',0),('printer',.2,.5))),
        B("Ergebnis: weggewischt nach einer Sekunde.",
          T(line(D('ERGEBNIS'),A('0', cls='red')), size='l'),
          obj={'type':'receipt','title':'ERSTE RECHNUNG · BEISPIEL','lines':[{'k':'DREHZEIT','v':'[[2 h]]','at':0},{'k':'SCHNITT','v':'[[3 h]]','at':0},{'k':'ABSTIMMUNG','v':'[[1 h]]','at':0},{'k':'ERGEBNIS','v':'0','tot':True,'red':True,'at':.4}],'at':-1,'printDur':.1},
          hud={'tcbar':{'start':.2,'dur':1.0}},
          layout='textTop', sfx=SFX(('hit',0),('printer',.3,.4),('stopp',1.2))),
        B("Das ist die erste Rechnung. Du hast sie bezahlt.",
          T(P('erste Rechnung'), A('Bezahlt'), size='l'),
          obj={'type':'receipt','title':'ERSTE RECHNUNG · BEISPIEL','lines':[{'k':'DREHZEIT','v':'[[2 h]]','at':0},{'k':'SCHNITT','v':'[[3 h]]','at':0},{'k':'ABSTIMMUNG','v':'[[1 h]]','at':0},{'k':'ERGEBNIS','v':'0','tot':True,'red':True,'at':0}],'at':-1,'printDur':.1,'tearAt':1.2},
          layout='textTop', sfx=SFX(('hit',0),('tear',1.2))),
        B("Jetzt die zweite.",
          T(A('Die zweite'), size='xl'),
          obj={'type':'receipt','title':'ZWEITE RECHNUNG','lines':[],'at':.2,'printDur':.6,'barcode':False},
          layout='textTop', sfx=SFX(('hit',0),('printer',.3))),
        B("Die Reichweite, die dein Video nicht bekommen hat, hat ein anderes bekommen.",
          T(P('die Reichweite'), A('hat ein anderer'), size='m'),
          obj={'type':'bars','items':[{'k':'du','v':3,'c':'r','suffix':'','at':.4},{'k':'?','v':88,'c':'grey','suffix':'','at':.8}]},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.8))),
        B("Dein Wettbewerb. Mit deiner Zielgruppe. In deiner Woche.",
          T(size='m'),
          obj={'type':'pills','items':[{'s':'dein Wettbewerb','cls':'red'},{'s':'deine Zielgruppe'},{'s':'deine Woche'}],'at':.2,'step':.4},
          layout='center', sfx=SFX(('hit',.2),('hit',.6),('hit',1.0))),
        B("Die holst du später zurück. Nur teurer.",
          T(P('später zurück'), A('Nur teurer'), size='l'),
          obj={'type':'receipt','title':'ZWEITE RECHNUNG','lines':[{'k':'NACHHOLEN','v':'[[…]]','at':.5},{'k':'REICHWEITE','v':'teurer','red':True,'at':.9}],'at':-1,'printDur':.1},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.5))),
        B("Zweimal bezahlt. Einmal für die Produktion, einmal für die Lücke.",
          T(A('Zweimal'), P('Produktion · Lücke'), size='l'),
          obj={'type':'cards','items':[{'icon':'film','label':'Produktion','n':1},{'icon':'persp','label':'Lücke','n':2}],'at':.4,'step':.3,'mode':'pop'},
          layout='textTop', sfx=SFX(('hit',0),('click',.4),('click',.7))),
        B("Der Unterschied zwischen „fertig“ und „gesehen“ sind die ersten null Komma fünf Sekunden und die Taktung danach.",
          T(line(K('Fertig'),A('≠ Gesehen')), D('0,5 s · 2–4 s','cap'), size='m'),
          obj={'type':'timeline','total':12,'marks':[2.5,5,8,10.5],'clips':6,'at':.6,'dur':2.6,'punchOnMark':True},
          hud={'tcbar':{'start':.2,'dur':1.7,'stopAt':.294}},
          layout='textTop', sfx=SFX(('hit',0),('stopp',.7),('click',1.6),('click',2.2),('click',2.8))),
        B("Zähl deine letzten zehn Videos. Wie viele wurden zu Ende gesehen? Schreib die Zahl.",
          T(A('Wie viele von 10?'), P('schreib die Zahl'), size='l'),
          obj={'type':'strip','n':10,'onAt':[[.3,9]],'hiAt':[[1.2,2],[1.5,6]],'at':.2},
          layout='textTop', sfx=SFX(('hit',0))+[{'name':'tick','at':.3+i*.06} for i in range(10)]),
    ]
    return {'slug':'mittelmass-kostet-doppelt','fps':25,'beats':beats,'ident':IDENT}
