from _dsl import *
# 15 · Aufmerksamkeit ist die Währung · Mittel (Mythos der Woche)
IDENT={'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}
def build():
    beats=[
        B("Follower sind nicht die Währung.",
          T(K('Follower'), A('sind nicht die Währung'), size='l'),
          obj={'type':'counter','from':100000,'to':100000,'sm':True,'at':0,'dur':.1,'outAt':1.4,'outDur':.7},
          layout='textTop', sfx=SFX(('hit',0),('pitchdown',1.4))),
        B("Mythos der Woche: „Mehr Follower, mehr Reichweite.“",
          T(L('Mythos der Woche','cap'), line(K('Mehr Follower ='),A('mehr Reichweite')), size='m'),
          obj={'type':'cards','items':[{'icon':'people','label':'Mythos','hi':True}],'at':.3,'mode':'pop','wide':True},
          layout='textTop', sfx=SFX(('stamp',.3),('hit',0))),
        B("Klingt logisch. Ist es nicht.",
          T(P('klingt logisch'), A('Ist es nicht'), size='l'),
          obj={'type':'cards','items':[{'icon':'people','label':'Mythos','dimAt':1.2}],'at':0,'mode':'pop','wide':True},
          cursors=[{'name':'CD','path':[[.5,300,1150],[1.2,780,1150]],'clicks':[.6]}],
          layout='textTop', sfx=SFX(('hit',0),('strike',.6),('tear',1.2))),
        B("Plattformen zeigen dein Video zuerst einem kleinen Teil.",
          T(P('zuerst'), A('Ein kleiner Teil'), size='m'),
          obj={'type':'slots','n':4,'labels':['','','',''],'onAt':[.4,.55,.7,.85],'at':.3,'w':180},
          layout='textTop', sfx=SFX(('hit',0),('click',.4),('click',.55),('click',.7),('click',.85))),
        B("Dann messen sie: Wer bleibt? Wie lange? Wer teilt?",
          T(P('dann messen sie'), size='m'),
          obj=[{'type':'pills','items':[{'s':'Wer bleibt?','at':.3},{'s':'Wie lange?','at':.7},{'s':'Wer teilt?','at':1.1}]},{'type':'curves','series':[{'c':'#3CC9B4','k':'hold','label':'Retention'}],'at':.5,'dur':1.6,'h':360,'mark3':False,'schem':False}],
          objGap=30, layout='textTop', sfx=SFX(('hit',0),('click',.3),('click',.7),('click',1.1))),
        B("Bleiben die Menschen, geht das Video an mehr. Bleiben sie nicht, endet es dort.",
          T(line(K('Bleiben →'),A('mehr', cls='teal')), line(K('Weg →'),A('Ende', cls='red')), size='m'),
          obj={'type':'split','items':[{'k':'bleiben','v':'×10','cls':'t','bar':.9},{'k':'weg','v':'Ende','cls':'r','bar':.06}],'at':.4,'step':.8},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.5),('stopp',1.4))),
        B("Dafür ist es egal, ob zweitausend oder hunderttausend Menschen dir folgen.",
          T(line(D('2.000'),K('oder'),D('100.000')), A('Egal'), size='m'),
          obj={'type':'counter','from':2000,'to':100000,'sm':True,'at':.3,'dur':1.4,'outAt':2.2,'outDur':.6},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.3),('pitchdown',2.2))),
        B("Schematisch: Account A, viele Follower, flaches Video. Account B, wenige Follower, Video wird gehalten.",
          T(line(D('A','red'),K('viele Follower ·'),D('B','teal'),K('wenige')), L('schematisch'), size='s'),
          obj={'type':'curves','series':[{'c':'#FF6B8B','k':'fall','label':'A · 100.000 Follower'},{'c':'#3CC9B4','k':'hold','label':'B · 2.000 Follower'}],'at':.4,'step':.5,'dur':1.8,'h':500},
          layout='textTop', sfx=SFX(('hit',0),('pitchdown',.6),('riser',1.0))),
        B("Aufmerksamkeit ist die Währung. Watch-Time ist der Kontostand.",
          T(K('Aufmerksamkeit'), A('ist die Währung'), F('Watch-Time', extra=.1), size='m'), bg='cap', punch=True, exit='fade',
          sfx=SFX(('drop',0))),
        B("Was das für dich heißt: Nicht Follower sammeln. Videos bauen, bei denen Menschen bleiben.",
          T(P('nicht sammeln'), A('Bleiben'), size='l'),
          obj={'type':'timeline','total':12,'marks':[2.5,5,8,10.5],'clips':6,'at':.6,'dur':2.6,'punchOnMark':True},
          hud={'tcbar':{'start':.2,'dur':1.7,'stopAt':.294}},
          layout='textTop', sfx=SFX(('hit',0),('stopp',.7),('click',1.6),('click',2.2))),
        B("Welchen Mythos sollen wir als Nächstes prüfen? Schreib ihn in die Kommentare.",
          T(A('Welcher Mythos?'), P('schreib ihn in die Kommentare'), size='l'),
          obj={'type':'comments','items':[{'name':'du','text':'Mythos: …','typing':True,'typeDur':.6,'at':.5,'time':'jetzt'}],'at':.5},
          layout='textTop', sfx=SFX(('hit',0))+[{'name':'type','at':.6+i*.09} for i in range(6)]),
    ]
    return {'slug':'aufmerksamkeit-ist-die-waehrung','fps':25,'beats':beats,'ident':IDENT}
