from _dsl import *
# 16 · Was du heute nicht postest · Mittel (Kalender als Spielfeld)
IDENT={'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}
def build():
    beats=[
        B("Was du heute nicht postest, postet dein Wettbewerb.",
          T(K('Was du heute nicht postest,'), A('postet dein Wettbewerb'), size='m'),
          obj={'type':'calendar','at':.2,'fills':[{'i':0,'c':'grey','at':1.6}],'height':120},
          layout='textTop', sfx=SFX(('hit',0),('click',1.6))),
        B("Deine Zielgruppe scrollt heute. Nicht nächsten Monat, wenn der Plan fertig ist.",
          T(P('deine Zielgruppe'), A('scrollt heute'), size='l'),
          obj={'type':'phone','screen':{'kind':'feed','speed':2.5,'cards':10},'scale':.56,'shift':[0,30],'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0),('scroll',.3,1.6))),
        B("Jeder leere Tag ist ein Tag, an dem jemand anderes die eins Komma sieben Sekunden bekommt.",
          T(P('jeder leere Tag'), A('1,7 Sekunden'), F('jemand anderes', extra=.1), size='m'),
          obj={'type':'calendar','at':0,'fills':[{'i':0,'c':'grey','at':0},{'i':1,'c':'grey','at':.8},{'i':2,'c':'grey','at':1.1},{'i':3,'c':'grey','at':1.4}],'height':120},
          layout='textTop', sfx=SFX(('hit',0),('click',.8),('click',1.1),('click',1.4))),
        B("Und Reichweite, die ein anderer bekommt, holst du später nur teurer zurück.",
          T(P('später'), A('Nur teurer'), size='l'),
          obj=[{'type':'bars','items':[{'k':'du','v':5,'c':'r','suffix':'','at':.3},{'k':'?','v':80,'c':'grey','suffix':'','at':.6}]},
               {'type':'receipt','title':'NACHHOLEN','lines':[{'k':'REICHWEITE','v':'teurer','red':True,'at':1.4}],'at':.9,'printDur':.8,'barcode':False}],
          objGap=10, layout='textTop', sfx=SFX(('hit',0),('rattle',.6),('printer',.9,.9))),
        B("Deshalb zählt nicht der perfekte Plan. Sondern der Rhythmus.",
          T(P('nicht der Plan'), A('Der Rhythmus'), size='l'),
          obj={'type':'calendar','at':.2,'fills':[{'i':0,'c':'cap','at':1.0},{'i':2,'c':'cap','at':1.2},{'i':4,'c':'cap','at':1.4}],'height':120},
          layout='textTop', sfx=SFX(('hit',0),('tick',1.0),('tick',1.2),('tick',1.4))),
        B("Drei Videos pro Woche. Fest im Kalender. Ab Tag sieben.",
          T(A('3 / Woche'), P('ab Tag 7'), size='xl'),
          obj={'type':'calendar','days':['T0','T1','T2','T3','T4','T5','T6','T7'],'strip':True,'at':.2,'fills':[{'i':i,'c':'grey','at':.4+i*.1} for i in range(7)]+[{'i':7,'c':'cap','at':1.3}],'height':100},
          layout='textTop', sfx=SFX(('hit',0))+[{'name':'tick','at':.4+i*.1} for i in range(7)]+[{'name':'hit','at':1.3}]),
        B("Ohne dass du jede Woche neu überlegen musst, was du postest.",
          T(P('ohne neu überlegen'), size='m'),
          obj=[{'type':'cards','items':[{'icon':'target','label':'Säule 1'},{'icon':'target','label':'Säule 2'},{'icon':'target','label':'Säule 3'}],'at':.3,'step':.15,'mode':'pop'},{'type':'pipeline','at':.9,'dur':2.0}],
          objGap=20, layout='textTop', sfx=SFX(('hit',0),('click',.3),('click',.45),('click',.6),('tick',1.2),('tick',1.7),('tick',2.2))),
        B("Dein Wettbewerb hat diese Woche schon gepostet. Was postest du?",
          T(P('diese Woche'), A('Was postest du?'), size='l'),
          obj={'type':'calendar','at':.2,'fills':[{'i':0,'c':'grey','at':.3},{'i':1,'c':'grey','at':.4},{'i':3,'c':'grey','at':.5},{'i':2,'c':'cap','at':1.3},{'i':4,'c':'cap','at':1.5},{'i':5,'c':'cap','at':1.7}],'height':120},
          layout='textTop', sfx=SFX(('hit',0),('click',.3),('click',.4),('click',.5),('tick',1.3),('tick',1.5),('tick',1.7))),
        B("Schick uns per DM, was gerade liegen bleibt. Wir machen daraus den ersten Monat.",
          T(A('Per DM'), P('was gerade liegen bleibt'), size='l'),
          obj={'type':'phone','screen':{'kind':'dm','title':'Daumenstopp','items':[{'name':'du','text':'Wir haben 40 Clips vom Messestand …'},{'name':'Daumenstopp','text':'Daraus bauen wir den ersten Monat.'}],'at':.4},'scale':.56,'shift':[0,30],'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0),('pling',.6),('pling',1.2))),
    ]
    return {'slug':'was-du-heute-nicht-postest','fps':25,'beats':beats,'ident':IDENT}
