from _dsl import *
# 17 · Der Tippfehler, der nie ankam · Mittel (Story)
IDENT={'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}
def ph(cap,extra=None):
    s={'kind':'clip','handle':'@kunde','caption':cap,'capCls':'plain','capAnim':False,'ui':False}
    if extra: s.update(extra)
    return {'type':'phone','screen':s,'scale':.56,'shift':[0,30],'mode':'rise'}
def build():
    beats=[
        B("Freitag, siebzehn Uhr zweiundvierzig. Das Video ist fertig. Fast.",
          T(D('FR · 17:42','cap'), K('Fertig.'), A('Fast.'), size='l'),
          obj={'type':'bars','items':[{'k':'','v':100,'c':'cap','label':'Export','suffix':' %','at':.3,'dur':1.4}]},
          cursors=[{'name':'Editor','path':[[1.6,900,1500],[2.0,860,1150]],'clicks':[2.05]}],
          layout='textTop', sfx=SFX(('hit',0),('rattle',.3),('pling',1.8),('click',2.05))),
        B("Der Editor hat es dreimal gesehen. Jeder Schnitt sitzt, der Sound sitzt, der Hook sitzt.",
          T(P('dreimal gesehen'), size='m'),
          obj={'type':'checklist','items':[{'s':'Schnitt','at':.4},{'s':'Sound','at':.8},{'s':'Hook','at':1.2}],'width':820},
          layout='textTop', sfx=SFX(('hit',0),('haken',.75),('haken',1.15),('haken',1.55))),
        B("Jetzt kommt der zweite Blick.",
          T(A('Der zweite Blick'), size='l'),
          obj=ph('Qualiät'),
          cursors=[{'name':'QC','path':[[.5,1000,1700],[1.2,760,1300]],'clicks':[1.25]}],
          layout='textTop', sfx=SFX(('hit',0),('click',1.25))),
        B("Nicht, weil der Editor schlecht ist. Weil man seine eigenen Fehler nicht mehr sieht.",
          T(P('nicht weil'), A('Eigene Fehler sieht man nicht'), size='m'),
          obj=ph('Qualiät'), layout='textTop', sfx=SFX(('hit',0))),
        B("Siebzehn Uhr sechsundvierzig. Der zweite Editor scrollt. Sekunde zwölf.",
          T(D('17:46','cap'), D('00:00:12:08'), size='l'),
          obj={'type':'timeline','total':20,'marks':[12],'clips':6,'at':.2,'dur':2.2,'markLabels':['12 s']},
          cursors=[{'name':'QC','path':[[.6,120,1300],[2.4,620,1300]],'clicks':[2.4]}],
          layout='textTop', sfx=SFX(('hit',0),('rattle',.6),('rattle',1.4),('stopp',2.4))),
        B("Da.",
          T(A('Da.', size='xl')), punch=.14, dur=1.4,
          obj=ph('Qualiät'), layout='textTop', sfx=SFX(('hit',0),('silence',.3))),
        B("„Qualiät.“ Ein Buchstabe fehlt. In einem Video über Qualität.",
          T(line(D('Quali','red'),D('_','red'),D('ät','red')), A('Ein Buchstabe'), F('über Qualität', extra=.1), size='m'),
          obj=ph('Qualiät'), layout='textTop', sfx=SFX(('hit',0),('buzz',.4))),
        B("Siebzehn Uhr neunundvierzig. Korrigiert. Neu exportiert.",
          T(D('17:49','cap'), A('Qualität', cls='teal'), size='l'),
          obj=ph('Qualität'),
          cursors=[{'name':'QC','path':[[.2,760,1300],[.6,700,1300]],'clicks':[.6]}],
          layout='textTop', sfx=SFX(('hit',0),('type',.6),('haken',.9),('pling',1.6))),
        B("Siebzehn Uhr einundfünfzig. Lieferung im Review-Link. Der Kunde sieht: ein fertiges Video.",
          T(D('17:51','cap'), A('Geliefert'), size='l'),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@kunde','caption':'*Qualität','capAt':.4},'scale':.56,'shift':[0,30],'mode':'rise','glow':True},
          layout='textTop', sfx=SFX(('hit',0),('pling',.4))),
        B("Den Tippfehler sieht er nie. Niemand sieht ihn.",
          T(P('niemand'), A('Nie'), size='xl'),
          obj={'type':'pills','items':[{'s':'Qualiät','cls':'red','outAt':.8}],'at':.1},
          layout='textTop', sfx=SFX(('hit',0),('pitchdown',.8))),
        B("Das ist das Vier-Augen-Prinzip. Bei jeder Lieferung. Ohne Ausnahme.",
          T(A('QC 2×'), P('jede Lieferung · ohne Ausnahme'), size='l'),
          cursors=[{'name':'Editor','path':[[.3,300,1150],[.3,300,1150]]},{'name':'QC','path':[[.5,640,1150],[.5,640,1150]]}],
          obj={'type':'cards','items':[{'icon':'eye','label':'Editor'},{'icon':'eye','label':'QC'}],'at':.3,'step':.2,'mode':'pop'},
          layout='textTop', sfx=SFX(('hit',0),('stamp',.8))),
        B("Ein Tippfehler in einem Video, das tausende Menschen sehen, ist kein kleiner Fehler.",
          T(P('tausende sehen'), A('Kein kleiner Fehler'), size='m'),
          obj={'type':'counter','from':0,'to':48210,'suffix':'','sm':True,'at':.3,'dur':1.8,'ease':'lin'},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.3),('rattle',1.0))),
        B("Wer prüft bei dir?",
          T(A('Wer prüft bei dir?'), size='l'),
          obj={'type':'comments','items':[{'name':'du','text':'…','typing':True,'typeDur':.2,'at':.5,'time':'jetzt'}],'at':.5},
          layout='textTop', sfx=SFX(('hit',0),('type',.6))),
    ]
    return {'slug':'der-tippfehler-der-nie-ankam','fps':25,'beats':beats,'ident':IDENT}
