from _dsl import *
# 19 · Wir haben kein Rohmaterial · Mittel (Bevor du fragst)
IDENT={'mode':'short','dur':2.2,'sfx':[('scroll',0,.55),('stopp',.5),('click',.78),('logo',.8)]}
DOC=['3 Sätze zum Produkt','Kamera auf Augenhöhe','Fenster im Rücken','20 Sekunden']
def build():
    beats=[
        B("„Wir haben kein Rohmaterial. Geht das trotzdem?“",
          T(L('Bevor du fragst','cap'), A('Kein Rohmaterial?'), size='l'),
          obj={'type':'cards','items':[{'icon':'film','label':'0 Dateien'}],'at':.4,'mode':'pop','wide':True},
          layout='textTop', sfx=SFX(('hit',0),('click',.4))),
        B("Ja. Auf drei Wegen.",
          T(K('Ja.'), A('Drei Wege'), size='xl'),
          obj={'type':'cards','items':[{'n':1,'icon':'doc','label':'Drehliste'},{'n':2,'icon':'camera','label':'Drehtag'},{'n':3,'icon':'mic','label':'Long-Form'}],'at':.4,'step':.15,'mode':'pop'},
          layout='textTop', sfx=SFX(('hit',0),('click',.4),('click',.55),('click',.7))),
        B("Weg eins. Du bekommst Drehlisten und Skripte.",
          T(line(D('1','cap'),A('Drehliste + Skript')), size='m'),
          obj={'type':'doc','title':'Drehliste · Produkt','lines':[{'s':s,'at':99} for s in DOC],'w':720},
          layout='textTop', sfx=SFX(('hit',0),('whoosh',.3))),
        B("So eine Liste sieht so aus: Drei Sätze zum Produkt, Kamera auf Augenhöhe, Fenster im Rücken, zwanzig Sekunden.",
          T(P('so sieht sie aus'), size='m'),
          obj={'type':'doc','title':'Drehliste · Produkt','lines':[{'s':DOC[0],'at':.5},{'s':DOC[1],'at':1.3},{'s':DOC[2],'at':2.1},{'s':DOC[3],'at':2.9}],'w':720},
          cursors=[{'name':'CD','path':[[.3,300,1100],[.5,300,1150],[1.3,300,1230],[2.1,300,1310],[2.9,300,1390]],'clicks':[.5,1.3,2.1,2.9]}],
          layout='textTop', sfx=SFX(('hit',0),('haken',.5),('haken',1.3),('haken',2.1),('haken',2.9))),
        B("Gefilmt mit dem Smartphone. Reicht völlig, wenn der Schnitt stimmt.",
          T(P('mit dem Smartphone'), A('Reicht'), size='l'),
          obj={'type':'phone','screen':{'kind':'clip','handle':'@du','ui':False,'caption':'Reicht *völlig','capAt':1.0},'scale':.56,'shift':[0,30],'mode':'rise'},
          layout='textTop', sfx=SFX(('hit',0),('shutter',.4),('pling',1.0))),
        B("Weg zwei. Ein Drehtag mit unserem Videografen.",
          T(line(D('2','cap'),A('Drehtag')), size='l'),
          obj={'type':'icobox','icon':'clap','size':300}, layout='textTop', sfx=SFX(('hit',0),('stamp',.3))),
        B("Ein Tag vor Ort, mit Licht und Ton. Material für zwanzig und mehr Videos.",
          T(P('ein Tag vor Ort'), A('20+ Videos'), size='l'),
          obj={'type':'counter','from':0,'to':20,'suffix':'+','at':.4,'dur':1.4,'stopPop':True},
          layout='textTop', sfx=SFX(('hit',0),('rattle',.4),('hit',1.8))),
        B("Weg drei. Ihr habt einen Podcast, Webinare, lange Videos?",
          T(line(D('3','cap'),A('Long-Form')), P('Podcast · Webinar · lange Videos'), size='m'),
          obj={'type':'wave','bars':64,'h':220,'freq':3}, layout='textTop', sfx=SFX(('hit',0))),
        B("Daraus schneiden wir Short-Form. Ein Podcast, zwölf Clips.",
          T(P('ein Podcast'), A('Zwölf Clips'), size='l'),
          obj={'type':'strip','n':12,'onAt':[[.4+i*.1,i] for i in range(12)],'at':.2},
          layout='textTop', sfx=SFX(('hit',0))+[{'name':'click','at':.4+i*.1} for i in range(12)]),
        B("Du filmst oder lieferst Material. Alles andere übernehmen wir.",
          T(P('du filmst'), A('Alles andere wir'), size='m'),
          obj={'type':'pipeline','at':.4,'dur':2.4},
          layout='textTop', sfx=SFX(('hit',0),('tick',.6),('tick',1.2),('tick',1.8),('tick',2.4))),
        B("Willst du die Beispiel-Drehliste? Kommentier DREHLISTE.",
          T(A('DREHLISTE', size='xl'), P('in die Kommentare'), size='m'),
          obj={'type':'comments','items':[{'name':'du','text':'DREHLISTE','typing':True,'typeDur':.8,'at':.4,'time':'jetzt'}],'at':.4},
          layout='textTop', sfx=SFX(('hit',0))+[{'name':'type','at':.5+i*.09} for i in range(9)]),
    ]
    return {'slug':'wir-haben-kein-rohmaterial','fps':25,'beats':beats,'ident':IDENT}
